import java.util.LinkedList;
import JSHOP2.*;

public class u09
{
	private static String[] defineConstants()
	{
		String[] problemConstants = new String[42];

		problemConstants[0] = "truck1";
		problemConstants[1] = "l3";
		problemConstants[2] = "a1";
		problemConstants[3] = "a2";
		problemConstants[4] = "a3";
		problemConstants[5] = "package1";
		problemConstants[6] = "package2";
		problemConstants[7] = "package3";
		problemConstants[8] = "package4";
		problemConstants[9] = "package5";
		problemConstants[10] = "package6";
		problemConstants[11] = "package7";
		problemConstants[12] = "l1";
		problemConstants[13] = "package8";
		problemConstants[14] = "package9";
		problemConstants[15] = "package10";
		problemConstants[16] = "l2";
		problemConstants[17] = "package11";
		problemConstants[18] = "l4";
		problemConstants[19] = "t0";
		problemConstants[20] = "t1";
		problemConstants[21] = "t2";
		problemConstants[22] = "t3";
		problemConstants[23] = "t4";
		problemConstants[24] = "t5";
		problemConstants[25] = "t6";
		problemConstants[26] = "t7";
		problemConstants[27] = "t8";
		problemConstants[28] = "t9";
		problemConstants[29] = "t10";
		problemConstants[30] = "t11";
		problemConstants[31] = "t12";
		problemConstants[32] = "t13";
		problemConstants[33] = "t14";
		problemConstants[34] = "t15";
		problemConstants[35] = "t16";
		problemConstants[36] = "t17";
		problemConstants[37] = "t18";
		problemConstants[38] = "t19";
		problemConstants[39] = "t20";
		problemConstants[40] = "t21";
		problemConstants[41] = "t22";

		return problemConstants;
	}

	private static void createState0(State s)	{
		s.add(new Predicate(15, 0, new TermList(TermConstant.getConstant(16), TermList.NIL)));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(16), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(1, 0, new TermList(TermConstant.getConstant(18), new TermList(TermConstant.getConstant(16), TermList.NIL))));
		s.add(new Predicate(1, 0, new TermList(TermConstant.getConstant(19), new TermList(TermConstant.getConstant(16), TermList.NIL))));
		s.add(new Predicate(1, 0, new TermList(TermConstant.getConstant(20), new TermList(TermConstant.getConstant(16), TermList.NIL))));
		s.add(new Predicate(2, 0, new TermList(TermConstant.getConstant(18), new TermList(TermConstant.getConstant(19), TermList.NIL))));
		s.add(new Predicate(2, 0, new TermList(TermConstant.getConstant(18), new TermList(TermConstant.getConstant(20), TermList.NIL))));
		s.add(new Predicate(2, 0, new TermList(TermConstant.getConstant(19), new TermList(TermConstant.getConstant(20), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(21), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(22), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(23), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(24), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(25), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(26), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(27), new TermList(TermConstant.getConstant(28), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(29), new TermList(TermConstant.getConstant(28), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(30), new TermList(TermConstant.getConstant(28), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(31), new TermList(TermConstant.getConstant(32), TermList.NIL))));
		s.add(new Predicate(0, 0, new TermList(TermConstant.getConstant(33), new TermList(TermConstant.getConstant(32), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(28), new TermList(TermConstant.getConstant(32), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(28), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(28), new TermList(TermConstant.getConstant(34), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(32), new TermList(TermConstant.getConstant(28), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(32), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(32), new TermList(TermConstant.getConstant(34), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(17), new TermList(TermConstant.getConstant(28), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(17), new TermList(TermConstant.getConstant(32), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(17), new TermList(TermConstant.getConstant(34), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(34), new TermList(TermConstant.getConstant(28), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(34), new TermList(TermConstant.getConstant(32), TermList.NIL))));
		s.add(new Predicate(4, 0, new TermList(TermConstant.getConstant(34), new TermList(TermConstant.getConstant(17), TermList.NIL))));
		s.add(new Predicate(5, 0, new TermList(TermConstant.getConstant(35), TermList.NIL)));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(36), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(37), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(38), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(39), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(40), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(37), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(38), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(39), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(40), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(38), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(39), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(40), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(39), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(40), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(40), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(53), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(53), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(53), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(53), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(53), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(54), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(54), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(54), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(54), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(55), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(55), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(55), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(56), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(56), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(7, 0, new TermList(TermConstant.getConstant(57), new TermList(TermConstant.getConstant(57), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(35), new TermList(TermConstant.getConstant(36), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(36), new TermList(TermConstant.getConstant(37), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(37), new TermList(TermConstant.getConstant(38), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(38), new TermList(TermConstant.getConstant(39), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(39), new TermList(TermConstant.getConstant(40), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(40), new TermList(TermConstant.getConstant(41), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(41), new TermList(TermConstant.getConstant(42), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(42), new TermList(TermConstant.getConstant(43), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(43), new TermList(TermConstant.getConstant(44), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(44), new TermList(TermConstant.getConstant(45), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(45), new TermList(TermConstant.getConstant(46), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(46), new TermList(TermConstant.getConstant(47), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(47), new TermList(TermConstant.getConstant(48), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(48), new TermList(TermConstant.getConstant(49), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(49), new TermList(TermConstant.getConstant(50), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(50), new TermList(TermConstant.getConstant(51), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(51), new TermList(TermConstant.getConstant(52), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(52), new TermList(TermConstant.getConstant(53), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(53), new TermList(TermConstant.getConstant(54), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(54), new TermList(TermConstant.getConstant(55), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(55), new TermList(TermConstant.getConstant(56), TermList.NIL))));
		s.add(new Predicate(6, 0, new TermList(TermConstant.getConstant(56), new TermList(TermConstant.getConstant(57), TermList.NIL))));
	}

	public static LinkedList<Plan> getPlans()
	{
		LinkedList<Plan> returnedPlans = new LinkedList<Plan>();
		TermConstant.initialize(58);

		Domain d = new trucks();

		d.setProblemConstants(defineConstants());

		State s = new State(16, d.getAxioms());

		JSHOP2.initialize(d, s);

		TaskList tl;
		SolverThread thread;

		createState0(s);

		tl = new TaskList(1, true);
		tl.subtasks[0] = new TaskList(new TaskAtom(new Predicate(0, 0, new TermList(new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(21), new TermList(TermConstant.getConstant(32), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(22), new TermList(TermConstant.getConstant(32), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(23), new TermList(TermConstant.getConstant(28), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(24), new TermList(TermConstant.getConstant(28), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(25), new TermList(TermConstant.getConstant(28), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(26), new TermList(TermConstant.getConstant(32), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(27), new TermList(TermConstant.getConstant(34), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(29), new TermList(TermConstant.getConstant(32), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(30), new TermList(TermConstant.getConstant(17), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(31), new TermList(TermConstant.getConstant(17), TermList.NIL))), new TermList(new TermList(TermConstant.getConstant(9), new TermList(TermConstant.getConstant(33), new TermList(TermConstant.getConstant(28), TermList.NIL))), TermList.NIL))))))))))), TermList.NIL)), false, false));

		thread = new SolverThread(tl, 1);
		thread.start();

		try {
			while (thread.isAlive())
				Thread.sleep(500);
		} catch (InterruptedException e) {
		}

		returnedPlans.addAll( thread.getPlans() );

		return returnedPlans;
	}

	public static LinkedList<Predicate> getFirstPlanOps() {
		return getPlans().getFirst().getOps();
	}
}