(defproblem p14  ROVER
  (
    ;;;
    ;;;  facts
    ;;;
    (LANDER GENERAL)
    (MODE COLOUR)
    (MODE HIGH_RES)
    (MODE LOW_RES)
    (ROVER ROVER0)
    (ROVER ROVER1)
    (ROVER ROVER2)
    (ROVER ROVER3)
    (STORE ROVER0STORE)
    (STORE ROVER1STORE)
    (STORE ROVER2STORE)
    (STORE ROVER3STORE)
    (WAYPOINT WAYPOINT0)
    (WAYPOINT WAYPOINT1)
    (WAYPOINT WAYPOINT2)
    (WAYPOINT WAYPOINT3)
    (WAYPOINT WAYPOINT4)
    (WAYPOINT WAYPOINT5)
    (WAYPOINT WAYPOINT6)
    (WAYPOINT WAYPOINT7)
    (WAYPOINT WAYPOINT8)
    (WAYPOINT WAYPOINT9)
    (CAMERA CAMERA0)
    (CAMERA CAMERA1)
    (CAMERA CAMERA2)
    (CAMERA CAMERA3)
    (CAMERA CAMERA4)
    (OBJECTIVE OBJECTIVE0)
    (OBJECTIVE OBJECTIVE1)
    (OBJECTIVE OBJECTIVE2)
    (OBJECTIVE OBJECTIVE3)
    ;;;
    ;;;  initial state Ts
    ;;;
    (VISIBLE WAYPOINT0 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT0)
    (VISIBLE WAYPOINT1 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT1)
    (VISIBLE WAYPOINT2 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT2)
    (VISIBLE WAYPOINT3 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT3)
    (VISIBLE WAYPOINT4 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT4)
    (VISIBLE WAYPOINT5 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT5)
    (VISIBLE WAYPOINT6 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT6)
    (VISIBLE WAYPOINT7 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT7)
    (VISIBLE WAYPOINT8 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT8)
    (VISIBLE WAYPOINT9 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT9)
    (AT_ROCK_SAMPLE WAYPOINT1)
    (AT_SOIL_SAMPLE WAYPOINT3)
    (AT_ROCK_SAMPLE WAYPOINT3)
    (AT_SOIL_SAMPLE WAYPOINT4)
    (AT_ROCK_SAMPLE WAYPOINT4)
    (AT_ROCK_SAMPLE WAYPOINT5)
    (AT_SOIL_SAMPLE WAYPOINT6)
    (AT_ROCK_SAMPLE WAYPOINT8)
    (AT_SOIL_SAMPLE WAYPOINT9)
    (AT_LANDER GENERAL WAYPOINT7)
    (CHANNEL_FREE GENERAL)
    (AT ROVER0 WAYPOINT1)
    (AVAILABLE ROVER0)
    (STORE_OF ROVER0STORE ROVER0)
    (EMPTY ROVER0STORE)
    (EQUIPPED_FOR_SOIL_ANALYSIS ROVER0)
    (EQUIPPED_FOR_IMAGING ROVER0)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT2)
    (CAN_TRAVERSE ROVER0 WAYPOINT2 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT6)
    (CAN_TRAVERSE ROVER0 WAYPOINT6 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT8)
    (CAN_TRAVERSE ROVER0 WAYPOINT8 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT2 WAYPOINT3)
    (CAN_TRAVERSE ROVER0 WAYPOINT3 WAYPOINT2)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT0)
    (CAN_TRAVERSE ROVER0 WAYPOINT0 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT5)
    (CAN_TRAVERSE ROVER0 WAYPOINT5 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT9)
    (CAN_TRAVERSE ROVER0 WAYPOINT9 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT8 WAYPOINT7)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT8)
    (AT ROVER1 WAYPOINT4)
    (AVAILABLE ROVER1)
    (STORE_OF ROVER1STORE ROVER1)
    (EMPTY ROVER1STORE)
    (EQUIPPED_FOR_SOIL_ANALYSIS ROVER1)
    (EQUIPPED_FOR_ROCK_ANALYSIS ROVER1)
    (EQUIPPED_FOR_IMAGING ROVER1)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT0)
    (CAN_TRAVERSE ROVER1 WAYPOINT0 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT5)
    (CAN_TRAVERSE ROVER1 WAYPOINT5 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT9)
    (CAN_TRAVERSE ROVER1 WAYPOINT9 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT0 WAYPOINT3)
    (CAN_TRAVERSE ROVER1 WAYPOINT3 WAYPOINT0)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT1)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT5 WAYPOINT7)
    (CAN_TRAVERSE ROVER1 WAYPOINT7 WAYPOINT5)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT8)
    (CAN_TRAVERSE ROVER1 WAYPOINT8 WAYPOINT6)
    (AT ROVER2 WAYPOINT0)
    (AVAILABLE ROVER2)
    (STORE_OF ROVER2STORE ROVER2)
    (EMPTY ROVER2STORE)
    (EQUIPPED_FOR_IMAGING ROVER2)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT3)
    (CAN_TRAVERSE ROVER2 WAYPOINT3 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT4)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT3 WAYPOINT2)
    (CAN_TRAVERSE ROVER2 WAYPOINT2 WAYPOINT3)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT1)
    (CAN_TRAVERSE ROVER2 WAYPOINT1 WAYPOINT4)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT5)
    (CAN_TRAVERSE ROVER2 WAYPOINT5 WAYPOINT4)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT8)
    (CAN_TRAVERSE ROVER2 WAYPOINT8 WAYPOINT4)
    (AT ROVER3 WAYPOINT2)
    (AVAILABLE ROVER3)
    (STORE_OF ROVER3STORE ROVER3)
    (EMPTY ROVER3STORE)
    (EQUIPPED_FOR_IMAGING ROVER3)
    (CAN_TRAVERSE ROVER3 WAYPOINT2 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT2)
    (CAN_TRAVERSE ROVER3 WAYPOINT2 WAYPOINT6)
    (CAN_TRAVERSE ROVER3 WAYPOINT6 WAYPOINT2)
    (CAN_TRAVERSE ROVER3 WAYPOINT2 WAYPOINT9)
    (CAN_TRAVERSE ROVER3 WAYPOINT9 WAYPOINT2)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT5)
    (CAN_TRAVERSE ROVER3 WAYPOINT5 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT7)
    (CAN_TRAVERSE ROVER3 WAYPOINT7 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT6 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT6)
    (CAN_TRAVERSE ROVER3 WAYPOINT6 WAYPOINT3)
    (CAN_TRAVERSE ROVER3 WAYPOINT3 WAYPOINT6)
    (CAN_TRAVERSE ROVER3 WAYPOINT6 WAYPOINT8)
    (CAN_TRAVERSE ROVER3 WAYPOINT8 WAYPOINT6)
    (ON_BOARD CAMERA0 ROVER3)
    (CALIBRATION_TARGET CAMERA0 OBJECTIVE2)
    (SUPPORTS CAMERA0 COLOUR)
    (SUPPORTS CAMERA0 LOW_RES)
    (ON_BOARD CAMERA1 ROVER2)
    (CALIBRATION_TARGET CAMERA1 OBJECTIVE3)
    (SUPPORTS CAMERA1 COLOUR)
    (ON_BOARD CAMERA2 ROVER1)
    (CALIBRATION_TARGET CAMERA2 OBJECTIVE3)
    (SUPPORTS CAMERA2 LOW_RES)
    (ON_BOARD CAMERA3 ROVER1)
    (CALIBRATION_TARGET CAMERA3 OBJECTIVE0)
    (SUPPORTS CAMERA3 COLOUR)
    (SUPPORTS CAMERA3 LOW_RES)
    (ON_BOARD CAMERA4 ROVER0)
    (CALIBRATION_TARGET CAMERA4 OBJECTIVE3)
    (SUPPORTS CAMERA4 COLOUR)
    (SUPPORTS CAMERA4 LOW_RES)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT6)
(preference_sb13_prev_autstate_1_2)
(preference_sb13_prev_autstate_2_2)
(preference_sb13_prev_autstate_3_2)
(preference_sb50_prev_autstate_1_2)
(preference_sb50_prev_autstate_2_2)
(preference_sb50_prev_autstate_3_2)
(preference_sb43_prev_autstate_1_2)
(preference_sb43_prev_autstate_2_2)
(preference_sb43_prev_autstate_3_2)
(preference_sb81_prev_autstate_1_2)
(preference_sb81_prev_autstate_2_2)
(preference_sb81_prev_autstate_3_2)
(preference_sb28_prev_autstate_1_2)
(preference_sb28_prev_autstate_2_2)
(preference_sb28_prev_autstate_3_2)
(preference_sb91_prev_autstate_1_2)
(preference_sb91_prev_autstate_2_2)
(preference_sb91_prev_autstate_3_2)
(preference_sb29_prev_autstate_1_2)
(preference_sb29_prev_autstate_2_2)
(preference_sb29_prev_autstate_3_2)
(preference_sb65_prev_autstate_1_2)
(preference_sb65_prev_autstate_2_2)
(preference_sb65_prev_autstate_3_2)
(preference_sb74_prev_autstate_1_2)
(preference_sb74_prev_autstate_2_2)
(preference_sb74_prev_autstate_3_2)
(preference_sb97_prev_autstate_1_2)
(preference_sb97_prev_autstate_2_2)
(preference_sb97_prev_autstate_3_2)
(preference_sb101_prev_autstate_1_2)
(preference_sb101_prev_autstate_2_2)
(preference_sb101_prev_autstate_3_2)
(preference_sb130_prev_autstate_1_2)
(preference_sb130_prev_autstate_2_2)
(preference_sb130_prev_autstate_3_2)
(preference_sb105_prev_autstate_1_2)
(preference_sb105_prev_autstate_2_2)
(preference_sb105_prev_autstate_3_2)
(preference_sb123_prev_autstate_1_2)
(preference_sb123_prev_autstate_2_2)
(preference_sb123_prev_autstate_3_2)
(preference_sb125_prev_autstate_1_2)
(preference_sb125_prev_autstate_2_2)
(preference_sb125_prev_autstate_3_2)
(preference_sb161_prev_autstate_1_2)
(preference_sb161_prev_autstate_2_2)
(preference_sb161_prev_autstate_3_2)
(preference_sb170_prev_autstate_1_2)
(preference_sb170_prev_autstate_2_2)
(preference_sb170_prev_autstate_3_2)
(preference_sb153_prev_autstate_1_2)
(preference_sb153_prev_autstate_2_2)
(preference_sb153_prev_autstate_3_2)
(preference_sb171_prev_autstate_1_2)
(preference_sb171_prev_autstate_2_2)
(preference_sb171_prev_autstate_3_2)
(preference_sb119_prev_autstate_1_2)
(preference_sb119_prev_autstate_2_2)
(preference_sb119_prev_autstate_3_2)
(preference_sb137_prev_autstate_1_2)
(preference_sb137_prev_autstate_2_2)
(preference_sb137_prev_autstate_3_2)
(preference_sb173_prev_autstate_1_2)
(preference_sb173_prev_autstate_2_2)
(preference_sb173_prev_autstate_3_2)
(preference_sb165_prev_autstate_1_2)
(preference_sb165_prev_autstate_2_2)
(preference_sb165_prev_autstate_3_2)
(preference_sb174_prev_autstate_1_2)
(preference_sb174_prev_autstate_2_2)
(preference_sb174_prev_autstate_3_2)
(preference_sb183_prev_autstate_1_2)
(preference_sb183_prev_autstate_2_2)
(preference_sb183_prev_autstate_3_2)
(preference_sb139_prev_autstate_1_2)
(preference_sb139_prev_autstate_2_2)
(preference_sb139_prev_autstate_3_2)
(preference_sb166_prev_autstate_1_2)
(preference_sb166_prev_autstate_2_2)
(preference_sb166_prev_autstate_3_2)
(preference_a0_prev_autstate_1_2)
(preference_a1_prev_autstate_1_2)
(preference_e0_prev_autstate_1_2)
(preference_e1_prev_autstate_1_2)
(preference_e2_prev_autstate_1_2)
(preference_e3_prev_autstate_1_2)
(preference_e4_prev_autstate_1_2)
(preference_e5_prev_autstate_1_2)
(preference_e6_prev_autstate_1_2)
(preference_e7_prev_autstate_1_2)
(preference_e8_prev_autstate_1_2)
(preference_e9_prev_autstate_1_2)
(preference_o0_prev_autstate_1_2)
(preference_o1_prev_autstate_1_2)
(preference_o2_prev_autstate_1_2)
(preference_o3_prev_autstate_1_2)
(preference_o4_prev_autstate_1_2)
(preference_o5_prev_autstate_1_2)
(preference_o6_prev_autstate_1_2)
(preference_o7_prev_autstate_1_2)
(preference_o8_prev_autstate_1_2)
(preference_o9_prev_autstate_1_2)
(preference_e10_prev_autstate_1_2)
(preference_e11_prev_autstate_1_2)
(preference_e20_prev_autstate_1_2)
(preference_e12_prev_autstate_1_2)
(preference_e13_prev_autstate_1_2)
(preference_e14_prev_autstate_1_2)
(preference_e15_prev_autstate_1_2)
(preference_e16_prev_autstate_1_2)
(preference_e17_prev_autstate_1_2)
(preference_e18_prev_autstate_1_2)
(preference_e19_prev_autstate_1_2)
(preference_sb13_prev_autstate_1_2)
(preference_sb13_prev_autstate_2_2)
(preference_sb13_prev_autstate_3_2)
(preference_sb50_prev_autstate_1_2)
(preference_sb50_prev_autstate_2_2)
(preference_sb50_prev_autstate_3_2)
(preference_sb43_prev_autstate_1_2)
(preference_sb43_prev_autstate_2_2)
(preference_sb43_prev_autstate_3_2)
(preference_sb81_prev_autstate_1_2)
(preference_sb81_prev_autstate_2_2)
(preference_sb81_prev_autstate_3_2)
(preference_sb28_prev_autstate_1_2)
(preference_sb28_prev_autstate_2_2)
(preference_sb28_prev_autstate_3_2)
(preference_sb91_prev_autstate_1_2)
(preference_sb91_prev_autstate_2_2)
(preference_sb91_prev_autstate_3_2)
(preference_sb29_prev_autstate_1_2)
(preference_sb29_prev_autstate_2_2)
(preference_sb29_prev_autstate_3_2)
(preference_sb65_prev_autstate_1_2)
(preference_sb65_prev_autstate_2_2)
(preference_sb65_prev_autstate_3_2)
(preference_sb74_prev_autstate_1_2)
(preference_sb74_prev_autstate_2_2)
(preference_sb74_prev_autstate_3_2)
(preference_sb97_prev_autstate_1_2)
(preference_sb97_prev_autstate_2_2)
(preference_sb97_prev_autstate_3_2)
(preference_sb101_prev_autstate_1_2)
(preference_sb101_prev_autstate_2_2)
(preference_sb101_prev_autstate_3_2)
(preference_sb130_prev_autstate_1_2)
(preference_sb130_prev_autstate_2_2)
(preference_sb130_prev_autstate_3_2)
(preference_sb105_prev_autstate_1_2)
(preference_sb105_prev_autstate_2_2)
(preference_sb105_prev_autstate_3_2)
(preference_sb123_prev_autstate_1_2)
(preference_sb123_prev_autstate_2_2)
(preference_sb123_prev_autstate_3_2)
(preference_sb125_prev_autstate_1_2)
(preference_sb125_prev_autstate_2_2)
(preference_sb125_prev_autstate_3_2)
(preference_sb161_prev_autstate_1_2)
(preference_sb161_prev_autstate_2_2)
(preference_sb161_prev_autstate_3_2)
(preference_sb170_prev_autstate_1_2)
(preference_sb170_prev_autstate_2_2)
(preference_sb170_prev_autstate_3_2)
(preference_sb153_prev_autstate_1_2)
(preference_sb153_prev_autstate_2_2)
(preference_sb153_prev_autstate_3_2)
(preference_sb171_prev_autstate_1_2)
(preference_sb171_prev_autstate_2_2)
(preference_sb171_prev_autstate_3_2)
(preference_sb119_prev_autstate_1_2)
(preference_sb119_prev_autstate_2_2)
(preference_sb119_prev_autstate_3_2)
(preference_sb137_prev_autstate_1_2)
(preference_sb137_prev_autstate_2_2)
(preference_sb137_prev_autstate_3_2)
(preference_sb173_prev_autstate_1_2)
(preference_sb173_prev_autstate_2_2)
(preference_sb173_prev_autstate_3_2)
(preference_sb165_prev_autstate_1_2)
(preference_sb165_prev_autstate_2_2)
(preference_sb165_prev_autstate_3_2)
(preference_sb174_prev_autstate_1_2)
(preference_sb174_prev_autstate_2_2)
(preference_sb174_prev_autstate_3_2)
(preference_sb183_prev_autstate_1_2)
(preference_sb183_prev_autstate_2_2)
(preference_sb183_prev_autstate_3_2)
(preference_sb139_prev_autstate_1_2)
(preference_sb139_prev_autstate_2_2)
(preference_sb139_prev_autstate_3_2)
(preference_sb166_prev_autstate_1_2)
(preference_sb166_prev_autstate_2_2)
(preference_sb166_prev_autstate_3_2)
(preference_a0_prev_autstate_1_2)
(preference_a1_prev_autstate_1_2)
(preference_e0_prev_autstate_1_2)
(preference_e1_prev_autstate_1_2)
(preference_e2_prev_autstate_1_2)
(preference_e3_prev_autstate_1_2)
(preference_e4_prev_autstate_1_2)
(preference_e5_prev_autstate_1_2)
(preference_e6_prev_autstate_1_2)
(preference_e7_prev_autstate_1_2)
(preference_e8_prev_autstate_1_2)
(preference_e9_prev_autstate_1_2)
(preference_o0_prev_autstate_1_2)
(preference_o1_prev_autstate_1_2)
(preference_o2_prev_autstate_1_2)
(preference_o3_prev_autstate_1_2)
(preference_o4_prev_autstate_1_2)
(preference_o5_prev_autstate_1_2)
(preference_o6_prev_autstate_1_2)
(preference_o7_prev_autstate_1_2)
(preference_o8_prev_autstate_1_2)
(preference_o9_prev_autstate_1_2)
(preference_e10_prev_autstate_1_2)
(preference_e11_prev_autstate_1_2)
(preference_e20_prev_autstate_1_2)
(preference_e12_prev_autstate_1_2)
(preference_e13_prev_autstate_1_2)
(preference_e14_prev_autstate_1_2)
(preference_e15_prev_autstate_1_2)
(preference_e16_prev_autstate_1_2)
(preference_e17_prev_autstate_1_2)
(preference_e18_prev_autstate_1_2)
(preference_e19_prev_autstate_1_2)

  )
  ;;;
  ;;; goals
  ;;;
 (:ordered (!!set-connectivity-info)
  ((achieve-goals (
    (COMMUNICATED_SOIL_DATA WAYPOINT3)
    (COMMUNICATED_SOIL_DATA WAYPOINT6)
    (COMMUNICATED_ROCK_DATA WAYPOINT5)
    (COMMUNICATED_ROCK_DATA WAYPOINT4)
    (COMMUNICATED_ROCK_DATA WAYPOINT8)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE0 COLOUR)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE2 LOW_RES)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE0 LOW_RES)
  ))))
)


(defun metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb183_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb174_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb173_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb170_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb166_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb165_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb161_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb153_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb139_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb137_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb130_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb125_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb123_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb119_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb105_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb101_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb97_satisfied) state))
(setq x (+ 43.710400 x)))
(if 
(null (find-satisfiers '(preference_sb43_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_o9_satisfied) state))
(setq x (+ 27.420800 x)))
(if 
(null (find-satisfiers '(preference_o8_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_o7_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_o6_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_o1_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e20_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e19_satisfied) state))
(setq x (+ 42.352900 x)))
(if 
(null (find-satisfiers '(preference_e18_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_e17_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_e16_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e15_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e14_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e13_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e12_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_e10_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e9_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e8_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e7_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_e6_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e5_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e4_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e3_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e1_satisfied) state))
(setq x (+ 26.063300 x)))
  (return-from metric x)
)
(defun pessimistic-metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb183_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb174_henceforth_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb173_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb170_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb166_henceforth_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb165_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb161_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb153_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb139_henceforth_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb137_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb130_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb125_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb123_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb119_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb105_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb101_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb97_henceforth_satisfied) state))
(setq x (+ 43.710400 x)))
(if 
(null (find-satisfiers '(preference_sb43_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_o9_henceforth_satisfied) state))
(setq x (+ 27.420800 x)))
(if 
(null (find-satisfiers '(preference_o8_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_o7_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_o6_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_o1_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e20_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e19_henceforth_satisfied) state))
(setq x (+ 42.352900 x)))
(if 
(null (find-satisfiers '(preference_e18_henceforth_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_e17_henceforth_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_e16_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e15_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e14_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e13_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e12_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_e10_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e9_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e8_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e7_henceforth_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_e6_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e5_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e4_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e3_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e1_henceforth_satisfied) state))
(setq x (+ 26.063300 x)))
  (return-from pessimistic-metric x)
)
(defun optimistic-metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb183_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb174_optimistically_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb173_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb170_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb166_optimistically_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb165_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb161_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb153_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb139_optimistically_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_sb137_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb130_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb125_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb123_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb119_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb105_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_sb101_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_sb97_optimistically_satisfied) state))
(setq x (+ 43.710400 x)))
(if 
(null (find-satisfiers '(preference_sb43_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_o9_optimistically_satisfied) state))
(setq x (+ 27.420800 x)))
(if 
(null (find-satisfiers '(preference_o8_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_o7_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_o6_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_o1_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e20_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e19_optimistically_satisfied) state))
(setq x (+ 42.352900 x)))
(if 
(null (find-satisfiers '(preference_e18_optimistically_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_e17_optimistically_satisfied) state))
(setq x (+ 39.909500 x)))
(if 
(null (find-satisfiers '(preference_e16_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e15_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e14_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e13_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e12_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_e10_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e9_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e8_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e7_optimistically_satisfied) state))
(setq x (+ 36.923100 x)))
(if 
(null (find-satisfiers '(preference_e6_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e5_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e4_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e3_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
(if 
(null (find-satisfiers '(preference_e1_optimistically_satisfied) state))
(setq x (+ 26.063300 x)))
  (return-from optimistic-metric x)
)




(defun bestMetric(&optional s)

  (return-from bestMetric  	 1868.69)
)