(defproblem p15  ROVER
  (
    ;;;
    ;;;  facts
    ;;;
    (LANDER GENERAL)
    (MODE COLOUR)
    (MODE HIGH_RES)
    (MODE LOW_RES)
    (ROVER ROVER0)
    (ROVER ROVER1)
    (ROVER ROVER2)
    (ROVER ROVER3)
    (STORE ROVER0STORE)
    (STORE ROVER1STORE)
    (STORE ROVER2STORE)
    (STORE ROVER3STORE)
    (WAYPOINT WAYPOINT0)
    (WAYPOINT WAYPOINT1)
    (WAYPOINT WAYPOINT2)
    (WAYPOINT WAYPOINT3)
    (WAYPOINT WAYPOINT4)
    (WAYPOINT WAYPOINT5)
    (WAYPOINT WAYPOINT6)
    (WAYPOINT WAYPOINT7)
    (WAYPOINT WAYPOINT8)
    (WAYPOINT WAYPOINT9)
    (WAYPOINT WAYPOINT10)
    (CAMERA CAMERA0)
    (CAMERA CAMERA1)
    (CAMERA CAMERA2)
    (CAMERA CAMERA3)
    (OBJECTIVE OBJECTIVE0)
    (OBJECTIVE OBJECTIVE1)
    (OBJECTIVE OBJECTIVE2)
    (OBJECTIVE OBJECTIVE3)
    (OBJECTIVE OBJECTIVE4)
    ;;;
    ;;;  initial state Ts
    ;;;
    (VISIBLE WAYPOINT0 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT0)
    (VISIBLE WAYPOINT1 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT1)
    (VISIBLE WAYPOINT2 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT2)
    (VISIBLE WAYPOINT3 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT3)
    (VISIBLE WAYPOINT4 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT4)
    (VISIBLE WAYPOINT5 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT5)
    (VISIBLE WAYPOINT7 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT7)
    (VISIBLE WAYPOINT8 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT8)
    (VISIBLE WAYPOINT9 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT9)
    (VISIBLE WAYPOINT10 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT10)
    (AT_SOIL_SAMPLE WAYPOINT0)
    (AT_ROCK_SAMPLE WAYPOINT1)
    (AT_SOIL_SAMPLE WAYPOINT2)
    (AT_ROCK_SAMPLE WAYPOINT2)
    (AT_SOIL_SAMPLE WAYPOINT4)
    (AT_SOIL_SAMPLE WAYPOINT5)
    (AT_SOIL_SAMPLE WAYPOINT7)
    (AT_SOIL_SAMPLE WAYPOINT8)
    (AT_ROCK_SAMPLE WAYPOINT8)
    (AT_ROCK_SAMPLE WAYPOINT9)
    (AT_SOIL_SAMPLE WAYPOINT10)
    (AT_ROCK_SAMPLE WAYPOINT10)
    (AT_LANDER GENERAL WAYPOINT9)
    (CHANNEL_FREE GENERAL)
    (AT ROVER0 WAYPOINT4)
    (AVAILABLE ROVER0)
    (STORE_OF ROVER0STORE ROVER0)
    (EMPTY ROVER0STORE)
    (EQUIPPED_FOR_SOIL_ANALYSIS ROVER0)
    (EQUIPPED_FOR_IMAGING ROVER0)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT0)
    (CAN_TRAVERSE ROVER0 WAYPOINT0 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT2)
    (CAN_TRAVERSE ROVER0 WAYPOINT2 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT5)
    (CAN_TRAVERSE ROVER0 WAYPOINT5 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT8)
    (CAN_TRAVERSE ROVER0 WAYPOINT8 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT9)
    (CAN_TRAVERSE ROVER0 WAYPOINT9 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT10)
    (CAN_TRAVERSE ROVER0 WAYPOINT10 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT0 WAYPOINT3)
    (CAN_TRAVERSE ROVER0 WAYPOINT3 WAYPOINT0)
    (CAN_TRAVERSE ROVER0 WAYPOINT0 WAYPOINT7)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT0)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT6)
    (CAN_TRAVERSE ROVER0 WAYPOINT6 WAYPOINT1)
    (AT ROVER1 WAYPOINT6)
    (AVAILABLE ROVER1)
    (STORE_OF ROVER1STORE ROVER1)
    (EMPTY ROVER1STORE)
    (EQUIPPED_FOR_IMAGING ROVER1)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT1)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT3)
    (CAN_TRAVERSE ROVER1 WAYPOINT3 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT5)
    (CAN_TRAVERSE ROVER1 WAYPOINT5 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT10)
    (CAN_TRAVERSE ROVER1 WAYPOINT10 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT0)
    (CAN_TRAVERSE ROVER1 WAYPOINT0 WAYPOINT1)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT7)
    (CAN_TRAVERSE ROVER1 WAYPOINT7 WAYPOINT1)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT8)
    (CAN_TRAVERSE ROVER1 WAYPOINT8 WAYPOINT1)
    (CAN_TRAVERSE ROVER1 WAYPOINT3 WAYPOINT9)
    (CAN_TRAVERSE ROVER1 WAYPOINT9 WAYPOINT3)
    (AT ROVER2 WAYPOINT6)
    (AVAILABLE ROVER2)
    (STORE_OF ROVER2STORE ROVER2)
    (EMPTY ROVER2STORE)
    (EQUIPPED_FOR_SOIL_ANALYSIS ROVER2)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT1)
    (CAN_TRAVERSE ROVER2 WAYPOINT1 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT4)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT5)
    (CAN_TRAVERSE ROVER2 WAYPOINT5 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT10)
    (CAN_TRAVERSE ROVER2 WAYPOINT10 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT1 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT1)
    (CAN_TRAVERSE ROVER2 WAYPOINT1 WAYPOINT7)
    (CAN_TRAVERSE ROVER2 WAYPOINT7 WAYPOINT1)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT2)
    (CAN_TRAVERSE ROVER2 WAYPOINT2 WAYPOINT4)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT3)
    (CAN_TRAVERSE ROVER2 WAYPOINT3 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT8)
    (CAN_TRAVERSE ROVER2 WAYPOINT8 WAYPOINT9)
    (AT ROVER3 WAYPOINT4)
    (AVAILABLE ROVER3)
    (STORE_OF ROVER3STORE ROVER3)
    (EMPTY ROVER3STORE)
    (EQUIPPED_FOR_ROCK_ANALYSIS ROVER3)
    (EQUIPPED_FOR_IMAGING ROVER3)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT2)
    (CAN_TRAVERSE ROVER3 WAYPOINT2 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT5)
    (CAN_TRAVERSE ROVER3 WAYPOINT5 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT6)
    (CAN_TRAVERSE ROVER3 WAYPOINT6 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT8)
    (CAN_TRAVERSE ROVER3 WAYPOINT8 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT9)
    (CAN_TRAVERSE ROVER3 WAYPOINT9 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT7)
    (CAN_TRAVERSE ROVER3 WAYPOINT7 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT3)
    (CAN_TRAVERSE ROVER3 WAYPOINT3 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT10)
    (CAN_TRAVERSE ROVER3 WAYPOINT10 WAYPOINT1)
    (ON_BOARD CAMERA0 ROVER3)
    (CALIBRATION_TARGET CAMERA0 OBJECTIVE2)
    (SUPPORTS CAMERA0 LOW_RES)
    (ON_BOARD CAMERA1 ROVER0)
    (CALIBRATION_TARGET CAMERA1 OBJECTIVE4)
    (SUPPORTS CAMERA1 COLOUR)
    (SUPPORTS CAMERA1 HIGH_RES)
    (SUPPORTS CAMERA1 LOW_RES)
    (ON_BOARD CAMERA2 ROVER1)
    (CALIBRATION_TARGET CAMERA2 OBJECTIVE4)
    (SUPPORTS CAMERA2 HIGH_RES)
    (SUPPORTS CAMERA2 LOW_RES)
    (ON_BOARD CAMERA3 ROVER1)
    (CALIBRATION_TARGET CAMERA3 OBJECTIVE3)
    (SUPPORTS CAMERA3 COLOUR)
    (SUPPORTS CAMERA3 HIGH_RES)
    (SUPPORTS CAMERA3 LOW_RES)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT9)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT10)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT9)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT9)
(preference_sb6_prev_autstate_1_2)
(preference_sb6_prev_autstate_2_2)
(preference_sb6_prev_autstate_3_2)
(preference_sb9_prev_autstate_1_2)
(preference_sb9_prev_autstate_2_2)
(preference_sb9_prev_autstate_3_2)
(preference_sb12_prev_autstate_1_2)
(preference_sb12_prev_autstate_2_2)
(preference_sb12_prev_autstate_3_2)
(preference_sb13_prev_autstate_1_2)
(preference_sb13_prev_autstate_2_2)
(preference_sb13_prev_autstate_3_2)
(preference_sb14_prev_autstate_1_2)
(preference_sb14_prev_autstate_2_2)
(preference_sb14_prev_autstate_3_2)
(preference_sb41_prev_autstate_1_2)
(preference_sb41_prev_autstate_2_2)
(preference_sb41_prev_autstate_3_2)
(preference_sb50_prev_autstate_1_2)
(preference_sb50_prev_autstate_2_2)
(preference_sb50_prev_autstate_3_2)
(preference_sb42_prev_autstate_1_2)
(preference_sb42_prev_autstate_2_2)
(preference_sb42_prev_autstate_3_2)
(preference_sb25_prev_autstate_1_2)
(preference_sb25_prev_autstate_2_2)
(preference_sb25_prev_autstate_3_2)
(preference_sb70_prev_autstate_1_2)
(preference_sb70_prev_autstate_2_2)
(preference_sb70_prev_autstate_3_2)
(preference_sb35_prev_autstate_1_2)
(preference_sb35_prev_autstate_2_2)
(preference_sb35_prev_autstate_3_2)
(preference_sb53_prev_autstate_1_2)
(preference_sb53_prev_autstate_2_2)
(preference_sb53_prev_autstate_3_2)
(preference_sb80_prev_autstate_1_2)
(preference_sb80_prev_autstate_2_2)
(preference_sb80_prev_autstate_3_2)
(preference_sb63_prev_autstate_1_2)
(preference_sb63_prev_autstate_2_2)
(preference_sb63_prev_autstate_3_2)
(preference_sb37_prev_autstate_1_2)
(preference_sb37_prev_autstate_2_2)
(preference_sb37_prev_autstate_3_2)
(preference_sb64_prev_autstate_1_2)
(preference_sb64_prev_autstate_2_2)
(preference_sb64_prev_autstate_3_2)
(preference_sb38_prev_autstate_1_2)
(preference_sb38_prev_autstate_2_2)
(preference_sb38_prev_autstate_3_2)
(preference_sb39_prev_autstate_1_2)
(preference_sb39_prev_autstate_2_2)
(preference_sb39_prev_autstate_3_2)
(preference_sb84_prev_autstate_1_2)
(preference_sb84_prev_autstate_2_2)
(preference_sb84_prev_autstate_3_2)
(preference_sb93_prev_autstate_1_2)
(preference_sb93_prev_autstate_2_2)
(preference_sb93_prev_autstate_3_2)
(preference_sb49_prev_autstate_1_2)
(preference_sb49_prev_autstate_2_2)
(preference_sb49_prev_autstate_3_2)
(preference_sb77_prev_autstate_1_2)
(preference_sb77_prev_autstate_2_2)
(preference_sb77_prev_autstate_3_2)
(preference_sb95_prev_autstate_1_2)
(preference_sb95_prev_autstate_2_2)
(preference_sb95_prev_autstate_3_2)
(preference_sb87_prev_autstate_1_2)
(preference_sb87_prev_autstate_2_2)
(preference_sb87_prev_autstate_3_2)
(preference_sb96_prev_autstate_1_2)
(preference_sb96_prev_autstate_2_2)
(preference_sb96_prev_autstate_3_2)
(preference_sb79_prev_autstate_1_2)
(preference_sb79_prev_autstate_2_2)
(preference_sb79_prev_autstate_3_2)
(preference_sb121_prev_autstate_1_2)
(preference_sb121_prev_autstate_2_2)
(preference_sb121_prev_autstate_3_2)
(preference_sb220_prev_autstate_1_2)
(preference_sb220_prev_autstate_2_2)
(preference_sb220_prev_autstate_3_2)
(preference_sb122_prev_autstate_1_2)
(preference_sb122_prev_autstate_2_2)
(preference_sb122_prev_autstate_3_2)
(preference_sb105_prev_autstate_1_2)
(preference_sb105_prev_autstate_2_2)
(preference_sb105_prev_autstate_3_2)
(preference_sb123_prev_autstate_1_2)
(preference_sb123_prev_autstate_2_2)
(preference_sb123_prev_autstate_3_2)
(preference_sb141_prev_autstate_1_2)
(preference_sb141_prev_autstate_2_2)
(preference_sb141_prev_autstate_3_2)
(preference_sb222_prev_autstate_1_2)
(preference_sb222_prev_autstate_2_2)
(preference_sb222_prev_autstate_3_2)
(preference_sb231_prev_autstate_1_2)
(preference_sb231_prev_autstate_2_2)
(preference_sb231_prev_autstate_3_2)
(preference_sb241_prev_autstate_1_2)
(preference_sb241_prev_autstate_2_2)
(preference_sb241_prev_autstate_3_2)
(preference_sb233_prev_autstate_1_2)
(preference_sb233_prev_autstate_2_2)
(preference_sb233_prev_autstate_3_2)
(preference_sb117_prev_autstate_1_2)
(preference_sb117_prev_autstate_2_2)
(preference_sb117_prev_autstate_3_2)
(preference_sb135_prev_autstate_1_2)
(preference_sb135_prev_autstate_2_2)
(preference_sb135_prev_autstate_3_2)
(preference_sb172_prev_autstate_1_2)
(preference_sb172_prev_autstate_2_2)
(preference_sb172_prev_autstate_3_2)
(preference_sb155_prev_autstate_1_2)
(preference_sb155_prev_autstate_2_2)
(preference_sb155_prev_autstate_3_2)
(preference_sb182_prev_autstate_1_2)
(preference_sb182_prev_autstate_2_2)
(preference_sb182_prev_autstate_3_2)
(preference_sb218_prev_autstate_1_2)
(preference_sb218_prev_autstate_2_2)
(preference_sb218_prev_autstate_3_2)
(preference_sb156_prev_autstate_1_2)
(preference_sb156_prev_autstate_2_2)
(preference_sb156_prev_autstate_3_2)
(preference_sb246_prev_autstate_1_2)
(preference_sb246_prev_autstate_2_2)
(preference_sb246_prev_autstate_3_2)
(preference_sb148_prev_autstate_1_2)
(preference_sb148_prev_autstate_2_2)
(preference_sb148_prev_autstate_3_2)
(preference_sb157_prev_autstate_1_2)
(preference_sb157_prev_autstate_2_2)
(preference_sb157_prev_autstate_3_2)
(preference_sb184_prev_autstate_1_2)
(preference_sb184_prev_autstate_2_2)
(preference_sb184_prev_autstate_3_2)
(preference_sb193_prev_autstate_1_2)
(preference_sb193_prev_autstate_2_2)
(preference_sb193_prev_autstate_3_2)
(preference_sb158_prev_autstate_1_2)
(preference_sb158_prev_autstate_2_2)
(preference_sb158_prev_autstate_3_2)
(preference_sb159_prev_autstate_1_2)
(preference_sb159_prev_autstate_2_2)
(preference_sb159_prev_autstate_3_2)
(preference_sb195_prev_autstate_1_2)
(preference_sb195_prev_autstate_2_2)
(preference_sb195_prev_autstate_3_2)
(preference_sb198_prev_autstate_1_2)
(preference_sb198_prev_autstate_2_2)
(preference_sb198_prev_autstate_3_2)
(preference_sb199_prev_autstate_1_2)
(preference_sb199_prev_autstate_2_2)
(preference_sb199_prev_autstate_3_2)
(preference_a0_prev_autstate_1_2)
(preference_a1_prev_autstate_1_2)
(preference_a2_prev_autstate_1_2)
(preference_e0_prev_autstate_1_2)
(preference_e1_prev_autstate_1_2)
(preference_e2_prev_autstate_1_2)
(preference_e3_prev_autstate_1_2)
(preference_e4_prev_autstate_1_2)
(preference_e5_prev_autstate_1_2)
(preference_e6_prev_autstate_1_2)
(preference_e7_prev_autstate_1_2)
(preference_e8_prev_autstate_1_2)
(preference_e9_prev_autstate_1_2)
(preference_o0_prev_autstate_1_2)
(preference_o1_prev_autstate_1_2)
(preference_o2_prev_autstate_1_2)
(preference_o3_prev_autstate_1_2)
(preference_o4_prev_autstate_1_2)
(preference_o5_prev_autstate_1_2)
(preference_o6_prev_autstate_1_2)
(preference_o7_prev_autstate_1_2)
(preference_o8_prev_autstate_1_2)
(preference_o9_prev_autstate_1_2)
(preference_e10_prev_autstate_1_2)
(preference_e11_prev_autstate_1_2)
(preference_e20_prev_autstate_1_2)
(preference_e12_prev_autstate_1_2)
(preference_e21_prev_autstate_1_2)
(preference_e30_prev_autstate_1_2)
(preference_e13_prev_autstate_1_2)
(preference_e22_prev_autstate_1_2)
(preference_e31_prev_autstate_1_2)
(preference_e14_prev_autstate_1_2)
(preference_e23_prev_autstate_1_2)
(preference_e32_prev_autstate_1_2)
(preference_e15_prev_autstate_1_2)
(preference_e24_prev_autstate_1_2)
(preference_e16_prev_autstate_1_2)
(preference_e25_prev_autstate_1_2)
(preference_e17_prev_autstate_1_2)
(preference_e26_prev_autstate_1_2)
(preference_e18_prev_autstate_1_2)
(preference_e27_prev_autstate_1_2)
(preference_e19_prev_autstate_1_2)
(preference_e28_prev_autstate_1_2)
(preference_e29_prev_autstate_1_2)
(preference_o10_prev_autstate_1_2)
(preference_o11_prev_autstate_1_2)
(preference_o12_prev_autstate_1_2)
(preference_o13_prev_autstate_1_2)
(preference_o14_prev_autstate_1_2)
(preference_sb6_prev_autstate_1_2)
(preference_sb6_prev_autstate_2_2)
(preference_sb6_prev_autstate_3_2)
(preference_sb9_prev_autstate_1_2)
(preference_sb9_prev_autstate_2_2)
(preference_sb9_prev_autstate_3_2)
(preference_sb12_prev_autstate_1_2)
(preference_sb12_prev_autstate_2_2)
(preference_sb12_prev_autstate_3_2)
(preference_sb13_prev_autstate_1_2)
(preference_sb13_prev_autstate_2_2)
(preference_sb13_prev_autstate_3_2)
(preference_sb14_prev_autstate_1_2)
(preference_sb14_prev_autstate_2_2)
(preference_sb14_prev_autstate_3_2)
(preference_sb41_prev_autstate_1_2)
(preference_sb41_prev_autstate_2_2)
(preference_sb41_prev_autstate_3_2)
(preference_sb50_prev_autstate_1_2)
(preference_sb50_prev_autstate_2_2)
(preference_sb50_prev_autstate_3_2)
(preference_sb42_prev_autstate_1_2)
(preference_sb42_prev_autstate_2_2)
(preference_sb42_prev_autstate_3_2)
(preference_sb25_prev_autstate_1_2)
(preference_sb25_prev_autstate_2_2)
(preference_sb25_prev_autstate_3_2)
(preference_sb70_prev_autstate_1_2)
(preference_sb70_prev_autstate_2_2)
(preference_sb70_prev_autstate_3_2)
(preference_sb35_prev_autstate_1_2)
(preference_sb35_prev_autstate_2_2)
(preference_sb35_prev_autstate_3_2)
(preference_sb53_prev_autstate_1_2)
(preference_sb53_prev_autstate_2_2)
(preference_sb53_prev_autstate_3_2)
(preference_sb80_prev_autstate_1_2)
(preference_sb80_prev_autstate_2_2)
(preference_sb80_prev_autstate_3_2)
(preference_sb63_prev_autstate_1_2)
(preference_sb63_prev_autstate_2_2)
(preference_sb63_prev_autstate_3_2)
(preference_sb37_prev_autstate_1_2)
(preference_sb37_prev_autstate_2_2)
(preference_sb37_prev_autstate_3_2)
(preference_sb64_prev_autstate_1_2)
(preference_sb64_prev_autstate_2_2)
(preference_sb64_prev_autstate_3_2)
(preference_sb38_prev_autstate_1_2)
(preference_sb38_prev_autstate_2_2)
(preference_sb38_prev_autstate_3_2)
(preference_sb39_prev_autstate_1_2)
(preference_sb39_prev_autstate_2_2)
(preference_sb39_prev_autstate_3_2)
(preference_sb84_prev_autstate_1_2)
(preference_sb84_prev_autstate_2_2)
(preference_sb84_prev_autstate_3_2)
(preference_sb93_prev_autstate_1_2)
(preference_sb93_prev_autstate_2_2)
(preference_sb93_prev_autstate_3_2)
(preference_sb49_prev_autstate_1_2)
(preference_sb49_prev_autstate_2_2)
(preference_sb49_prev_autstate_3_2)
(preference_sb77_prev_autstate_1_2)
(preference_sb77_prev_autstate_2_2)
(preference_sb77_prev_autstate_3_2)
(preference_sb95_prev_autstate_1_2)
(preference_sb95_prev_autstate_2_2)
(preference_sb95_prev_autstate_3_2)
(preference_sb87_prev_autstate_1_2)
(preference_sb87_prev_autstate_2_2)
(preference_sb87_prev_autstate_3_2)
(preference_sb96_prev_autstate_1_2)
(preference_sb96_prev_autstate_2_2)
(preference_sb96_prev_autstate_3_2)
(preference_sb79_prev_autstate_1_2)
(preference_sb79_prev_autstate_2_2)
(preference_sb79_prev_autstate_3_2)
(preference_sb121_prev_autstate_1_2)
(preference_sb121_prev_autstate_2_2)
(preference_sb121_prev_autstate_3_2)
(preference_sb220_prev_autstate_1_2)
(preference_sb220_prev_autstate_2_2)
(preference_sb220_prev_autstate_3_2)
(preference_sb122_prev_autstate_1_2)
(preference_sb122_prev_autstate_2_2)
(preference_sb122_prev_autstate_3_2)
(preference_sb105_prev_autstate_1_2)
(preference_sb105_prev_autstate_2_2)
(preference_sb105_prev_autstate_3_2)
(preference_sb123_prev_autstate_1_2)
(preference_sb123_prev_autstate_2_2)
(preference_sb123_prev_autstate_3_2)
(preference_sb141_prev_autstate_1_2)
(preference_sb141_prev_autstate_2_2)
(preference_sb141_prev_autstate_3_2)
(preference_sb222_prev_autstate_1_2)
(preference_sb222_prev_autstate_2_2)
(preference_sb222_prev_autstate_3_2)
(preference_sb231_prev_autstate_1_2)
(preference_sb231_prev_autstate_2_2)
(preference_sb231_prev_autstate_3_2)
(preference_sb241_prev_autstate_1_2)
(preference_sb241_prev_autstate_2_2)
(preference_sb241_prev_autstate_3_2)
(preference_sb233_prev_autstate_1_2)
(preference_sb233_prev_autstate_2_2)
(preference_sb233_prev_autstate_3_2)
(preference_sb117_prev_autstate_1_2)
(preference_sb117_prev_autstate_2_2)
(preference_sb117_prev_autstate_3_2)
(preference_sb135_prev_autstate_1_2)
(preference_sb135_prev_autstate_2_2)
(preference_sb135_prev_autstate_3_2)
(preference_sb172_prev_autstate_1_2)
(preference_sb172_prev_autstate_2_2)
(preference_sb172_prev_autstate_3_2)
(preference_sb155_prev_autstate_1_2)
(preference_sb155_prev_autstate_2_2)
(preference_sb155_prev_autstate_3_2)
(preference_sb182_prev_autstate_1_2)
(preference_sb182_prev_autstate_2_2)
(preference_sb182_prev_autstate_3_2)
(preference_sb218_prev_autstate_1_2)
(preference_sb218_prev_autstate_2_2)
(preference_sb218_prev_autstate_3_2)
(preference_sb156_prev_autstate_1_2)
(preference_sb156_prev_autstate_2_2)
(preference_sb156_prev_autstate_3_2)
(preference_sb246_prev_autstate_1_2)
(preference_sb246_prev_autstate_2_2)
(preference_sb246_prev_autstate_3_2)
(preference_sb148_prev_autstate_1_2)
(preference_sb148_prev_autstate_2_2)
(preference_sb148_prev_autstate_3_2)
(preference_sb157_prev_autstate_1_2)
(preference_sb157_prev_autstate_2_2)
(preference_sb157_prev_autstate_3_2)
(preference_sb184_prev_autstate_1_2)
(preference_sb184_prev_autstate_2_2)
(preference_sb184_prev_autstate_3_2)
(preference_sb193_prev_autstate_1_2)
(preference_sb193_prev_autstate_2_2)
(preference_sb193_prev_autstate_3_2)
(preference_sb158_prev_autstate_1_2)
(preference_sb158_prev_autstate_2_2)
(preference_sb158_prev_autstate_3_2)
(preference_sb159_prev_autstate_1_2)
(preference_sb159_prev_autstate_2_2)
(preference_sb159_prev_autstate_3_2)
(preference_sb195_prev_autstate_1_2)
(preference_sb195_prev_autstate_2_2)
(preference_sb195_prev_autstate_3_2)
(preference_sb198_prev_autstate_1_2)
(preference_sb198_prev_autstate_2_2)
(preference_sb198_prev_autstate_3_2)
(preference_sb199_prev_autstate_1_2)
(preference_sb199_prev_autstate_2_2)
(preference_sb199_prev_autstate_3_2)
(preference_a0_prev_autstate_1_2)
(preference_a1_prev_autstate_1_2)
(preference_a2_prev_autstate_1_2)
(preference_e0_prev_autstate_1_2)
(preference_e1_prev_autstate_1_2)

(preference_o0_prev_autstate_1_2)
(preference_o1_prev_autstate_1_2)
(preference_o2_prev_autstate_1_2)
(preference_o3_prev_autstate_1_2)
(preference_o4_prev_autstate_1_2)
(preference_o5_prev_autstate_1_2)
(preference_o6_prev_autstate_1_2)
(preference_o7_prev_autstate_1_2)
(preference_o8_prev_autstate_1_2)
(preference_o9_prev_autstate_1_2)
(preference_e10_prev_autstate_1_2)
(preference_e11_prev_autstate_1_2)
(preference_e20_prev_autstate_1_2)
(preference_e12_prev_autstate_1_2)
(preference_e21_prev_autstate_1_2)
(preference_e30_prev_autstate_1_2)
(preference_e13_prev_autstate_1_2)
(preference_e22_prev_autstate_1_2)
(preference_e31_prev_autstate_1_2)
(preference_e14_prev_autstate_1_2)
(preference_e23_prev_autstate_1_2)
(preference_e32_prev_autstate_1_2)
(preference_e15_prev_autstate_1_2)
(preference_e24_prev_autstate_1_2)
(preference_e16_prev_autstate_1_2)
(preference_e25_prev_autstate_1_2)
(preference_e17_prev_autstate_1_2)
(preference_e26_prev_autstate_1_2)
(preference_e18_prev_autstate_1_2)
(preference_e27_prev_autstate_1_2)
(preference_e19_prev_autstate_1_2)
(preference_e28_prev_autstate_1_2)
(preference_e29_prev_autstate_1_2)
(preference_o10_prev_autstate_1_2)
(preference_o11_prev_autstate_1_2)
(preference_o12_prev_autstate_1_2)
(preference_o13_prev_autstate_1_2)
(preference_o14_prev_autstate_1_2)

  )
  ;;;
  ;;; goals
  ;;;
(:ordered (!!set-connectivity-info)
  ((achieve-goals (
    (COMMUNICATED_SOIL_DATA WAYPOINT5)
    (COMMUNICATED_SOIL_DATA WAYPOINT2)
    (COMMUNICATED_SOIL_DATA WAYPOINT8)
    (COMMUNICATED_SOIL_DATA WAYPOINT10)
    (COMMUNICATED_SOIL_DATA WAYPOINT0)
    (COMMUNICATED_ROCK_DATA WAYPOINT2)
    (COMMUNICATED_ROCK_DATA WAYPOINT1)
    (COMMUNICATED_ROCK_DATA WAYPOINT8)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE1 LOW_RES)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE1 HIGH_RES)
  ))))
)


(defun metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb246_satisfied) state T))
(setq x (+ 75.036000 x)))
(if 
(null (find-satisfiers '(preference_sb241_satisfied) state T))
(setq x (+ 68.640000 x)))
(if 
(null (find-satisfiers '(preference_sb233_satisfied) state T))
(setq x (+ 33.748000 x)))
(if 
(null (find-satisfiers '(preference_sb231_satisfied) state T))
(setq x (+ 63.648000 x)))

(if 
(null (find-satisfiers '(preference_sb218_satisfied) state T))
(setq x (+ 35.949300 x)))
(if 
(null (find-satisfiers '(preference_sb199_satisfied) state T))
(setq x (+ 44.044000 x)))
(if 
(null (find-satisfiers '(preference_sb198_satisfied) state T))
(setq x (+ 60.060000 x)))
(if 
(null (find-satisfiers '(preference_sb195_satisfied) state T))
(setq x (+ 30.316000 x)))
(if 
(null (find-satisfiers '(preference_sb193_satisfied) state T))
(setq x (+ 41.520300 x)))
(if 
(null (find-satisfiers '(preference_sb184_satisfied) state T))
(setq x (+ 51.480000 x)))
;(if 
;(null (find-satisfiers '(preference_sb182_satisfied) state T))
;(setq x (+ 35.464000 x)))
(if 
(null (find-satisfiers '(preference_sb172_satisfied) state T))
(setq x (+ 91.728000 x)))
(if 
(null (find-satisfiers '(preference_sb159_satisfied) state T))
(setq x (+ 55.986700 x)))
(if 
(null (find-satisfiers '(preference_sb158_satisfied) state T))
(setq x (+ 53.404000 x)))
(if 
(null (find-satisfiers '(preference_sb157_satisfied) state T))
(setq x (+ 45.188000 x)))
(if 
(null (find-satisfiers '(preference_sb156_satisfied) state T))
(setq x (+ 55.484000 x)))
(if 
(null (find-satisfiers '(preference_sb155_satisfied) state T))
(setq x (+ 80.652000 x)))
(if 
(null (find-satisfiers '(preference_sb148_satisfied) state T))
(setq x (+ 42.224000 x)))
;(if 
;(null (find-satisfiers '(preference_sb141_satisfied) state T))
;(setq x (+ 29.744000 x)))
(if 
(null (find-satisfiers '(preference_sb135_satisfied) state T))
(setq x (+ 47.853900 x)))
(if 
(null (find-satisfiers '(preference_sb123_satisfied) state T))
(setq x (+ 54.912000 x)))
(if 
(null (find-satisfiers '(preference_sb122_satisfied) state T))
(setq x (+ 42.900000 x)))
(if 
(null (find-satisfiers '(preference_sb121_satisfied) state T))
(setq x (+ 72.072000 x)))
(if 
(null (find-satisfiers '(preference_sb117_satisfied) state T))
(setq x (+ 69.212000 x)))
(if 
(null (find-satisfiers '(preference_sb105_satisfied) state T))
(setq x (+ 90.521600 x)))
(if 
(null (find-satisfiers '(preference_sb96_satisfied) state T))
(setq x (+ 44.044000 x)))
(if 
(null (find-satisfiers '(preference_sb95_satisfied) state T))
(setq x (+ 91.291200 x)))
(if 
(null (find-satisfiers '(preference_sb93_satisfied) state T))
(setq x (+ 63.336000 x)))
(if 
(null (find-satisfiers '(preference_sb87_satisfied) state T))
(setq x (+ 83.744300 x)))

(if 
(null (find-satisfiers '(preference_sb80_satisfied) state T))
(setq x (+ 75.434700 x)))
(if 
(null (find-satisfiers '(preference_sb79_satisfied) state T))
(setq x (+ 30.888000 x)))
(if 
(null (find-satisfiers '(preference_sb77_satisfied) state T))
(setq x (+ 64.896000 x)))


(if 
(null (find-satisfiers '(preference_sb63_satisfied) state T))
(setq x (+ 70.356000 x)))
(if 
(null (find-satisfiers '(preference_sb53_satisfied) state T))
(setq x (+ 64.064000 x)))
(if 
(null (find-satisfiers '(preference_sb50_satisfied) state T))
(setq x (+ 41.184000 x)))
(if 
(null (find-satisfiers '(preference_sb49_satisfied) state T))
(setq x (+ 98.522700 x)))


(if 
(null (find-satisfiers '(preference_sb37_satisfied) state T))
(setq x (+ 54.912000 x)))


(if 
(null (find-satisfiers '(preference_sb9_satisfied) state T))
(setq x (+ 94.057600 x)))
(if 
(null (find-satisfiers '(preference_sb6_satisfied) state T))
(setq x (+ 102.745000 x)))
(if 
(null (find-satisfiers '(preference_o14_satisfied) state T))
(setq x (+ 51.480000 x)))
(if 
(null (find-satisfiers '(preference_o13_satisfied) state T))
(setq x (+ 82.506700 x)))
(if 
(null (find-satisfiers '(preference_o12_satisfied) state T))
(setq x (+ 54.340000 x)))
(if 
(null (find-satisfiers '(preference_o11_satisfied) state T))
(setq x (+ 33.176000 x)))
(if 
(null (find-satisfiers '(preference_o10_satisfied) state T))
(setq x (+ 59.488000 x)))
(if 
(null (find-satisfiers '(preference_o9_satisfied) state T))
(setq x (+ 32.604000 x)))
(if 
(null (find-satisfiers '(preference_o8_satisfied) state T))
(setq x (+ 61.776000 x)))
(if 
(null (find-satisfiers '(preference_o7_satisfied) state T))
(setq x (+ 82.940000 x)))
(if 
(null (find-satisfiers '(preference_o6_satisfied) state T))
(setq x (+ 63.058700 x)))
(if 
(null (find-satisfiers '(preference_o5_satisfied) state T))
(setq x (+ 57.238100 x)))
(if 
(null (find-satisfiers '(preference_o4_satisfied) state T))
(setq x (+ 53.404000 x)))
(if 
(null (find-satisfiers '(preference_o3_satisfied) state T))
(setq x (+ 39.468000 x)))
(if 
(null (find-satisfiers '(preference_o2_satisfied) state T))
(setq x (+ 39.468000 x)))
(if 
(null (find-satisfiers '(preference_o1_satisfied) state T))
(setq x (+ 98.536500 x)))
(if 
(null (find-satisfiers '(preference_o0_satisfied) state T))
(setq x (+ 63.492000 x)))
(if 
(null (find-satisfiers '(preference_e32_satisfied) state T))
(setq x (+ 53.768000 x)))
(if 
(null (find-satisfiers '(preference_e31_satisfied) state T))
(setq x (+ 82.940000 x)))
(if 
(null (find-satisfiers '(preference_e30_satisfied) state T))
(setq x (+ 96.668000 x)))
(if 
(null (find-satisfiers '(preference_e29_satisfied) state T))
(setq x (+ 63.058700 x)))
(if 
(null (find-satisfiers '(preference_e28_satisfied) state T))
(setq x (+ 80.149300 x)))
;;(if 
;;(null (find-satisfiers '(preference_e27_satisfied) state T))
;;(setq x (+ 69.628000 x)))
(if 
(null (find-satisfiers '(preference_e26_satisfied) state T))
(setq x (+ 58.344000 x)))
(if 
(null (find-satisfiers '(preference_e25_satisfied) state T))
(setq x (+ 35.464000 x)))
(if 
(null (find-satisfiers '(preference_e24_satisfied) state T))
(setq x (+ 66.924000 x)))

(if 
(null (find-satisfiers '(preference_e22_satisfied) state T))
(setq x (+ 74.360000 x)))
(if 
(null (find-satisfiers '(preference_e21_satisfied) state T))
(setq x (+ 63.648000 x)))
(if 
(null (find-satisfiers '(preference_e20_satisfied) state T))
(setq x (+ 50.336000 x)))
(if 
(null (find-satisfiers '(preference_e19_satisfied) state T))
(setq x (+ 65.447200 x)))
(if 
(null (find-satisfiers '(preference_e18_satisfied) state T))
(setq x (+ 77.740000 x)))
(if 
(null (find-satisfiers '(preference_e17_satisfied) state T))
(setq x (+ 73.666700 x)))

(if 
(null (find-satisfiers '(preference_e15_satisfied) state T))
(setq x (+ 85.800000 x)))
(if 
(null (find-satisfiers '(preference_e14_satisfied) state T))
(setq x (+ 86.632000 x)))

(if 
(null (find-satisfiers '(preference_e10_satisfied) state T))
(setq x (+ 37.297900 x)))

(if 
(null (find-satisfiers '(preference_e1_satisfied) state T))
(setq x (+ 59.522700 x)))
(if 
(null (find-satisfiers '(preference_e0_satisfied) state T))
(setq x (+ 70.720000 x)))
(if 
(null (find-satisfiers '(preference_a2_satisfied) state T))
(setq x (+ 42.900000 x)))
(if 
(null (find-satisfiers '(preference_a1_satisfied) state T))
(setq x (+ 72.072000 x)))

  (return-from metric x)
)
(defun pessimistic-metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb246_henceforth_satisfied) state T))
(setq x (+ 75.036000 x)))
(if 
(null (find-satisfiers '(preference_sb241_henceforth_satisfied) state T))
(setq x (+ 68.640000 x)))
(if 
(null (find-satisfiers '(preference_sb233_henceforth_satisfied) state T))
(setq x (+ 33.748000 x)))
(if 
(null (find-satisfiers '(preference_sb231_henceforth_satisfied) state T))
(setq x (+ 63.648000 x)))
(if 
(null (find-satisfiers '(preference_sb218_henceforth_satisfied) state T))
(setq x (+ 35.949300 x)))
(if 
(null (find-satisfiers '(preference_sb199_henceforth_satisfied) state T))
(setq x (+ 44.044000 x)))
(if 
(null (find-satisfiers '(preference_sb198_henceforth_satisfied) state T))
(setq x (+ 60.060000 x)))
(if 
(null (find-satisfiers '(preference_sb195_henceforth_satisfied) state T))
(setq x (+ 30.316000 x)))
(if 
(null (find-satisfiers '(preference_sb193_henceforth_satisfied) state T))
(setq x (+ 41.520300 x)))
(if 
(null (find-satisfiers '(preference_sb184_henceforth_satisfied) state T))
(setq x (+ 51.480000 x)))

(if 
(null (find-satisfiers '(preference_sb172_henceforth_satisfied) state T))
(setq x (+ 91.728000 x)))
(if 
(null (find-satisfiers '(preference_sb159_henceforth_satisfied) state T))
(setq x (+ 55.986700 x)))
(if 
(null (find-satisfiers '(preference_sb158_henceforth_satisfied) state T))
(setq x (+ 53.404000 x)))
(if 
(null (find-satisfiers '(preference_sb157_henceforth_satisfied) state T))
(setq x (+ 45.188000 x)))
(if 
(null (find-satisfiers '(preference_sb156_henceforth_satisfied) state T))
(setq x (+ 55.484000 x)))
(if 
(null (find-satisfiers '(preference_sb155_henceforth_satisfied) state T))
(setq x (+ 80.652000 x)))
(if 
(null (find-satisfiers '(preference_sb148_henceforth_satisfied) state T))
(setq x (+ 42.224000 x)))

(if 
(null (find-satisfiers '(preference_sb135_henceforth_satisfied) state T))
(setq x (+ 47.853900 x)))
(if 
(null (find-satisfiers '(preference_sb123_henceforth_satisfied) state T))
(setq x (+ 54.912000 x)))
(if 
(null (find-satisfiers '(preference_sb122_henceforth_satisfied) state T))
(setq x (+ 42.900000 x)))
(if 
(null (find-satisfiers '(preference_sb121_henceforth_satisfied) state T))
(setq x (+ 72.072000 x)))
(if 
(null (find-satisfiers '(preference_sb117_henceforth_satisfied) state T))
(setq x (+ 69.212000 x)))
(if 
(null (find-satisfiers '(preference_sb105_henceforth_satisfied) state T))
(setq x (+ 90.521600 x)))
(if 
(null (find-satisfiers '(preference_sb96_henceforth_satisfied) state T))
(setq x (+ 44.044000 x)))
(if 
(null (find-satisfiers '(preference_sb95_henceforth_satisfied) state T))
(setq x (+ 91.291200 x)))
(if 
(null (find-satisfiers '(preference_sb93_henceforth_satisfied) state T))
(setq x (+ 63.336000 x)))
(if 
(null (find-satisfiers '(preference_sb87_henceforth_satisfied) state T))
(setq x (+ 83.744300 x)))

(if 
(null (find-satisfiers '(preference_sb80_henceforth_satisfied) state T))
(setq x (+ 75.434700 x)))
(if 
(null (find-satisfiers '(preference_sb79_henceforth_satisfied) state T))
(setq x (+ 30.888000 x)))
(if 
(null (find-satisfiers '(preference_sb77_henceforth_satisfied) state T))
(setq x (+ 64.896000 x)))

(if 
(null (find-satisfiers '(preference_sb63_henceforth_satisfied) state T))
(setq x (+ 70.356000 x)))
(if 
(null (find-satisfiers '(preference_sb53_henceforth_satisfied) state T))
(setq x (+ 64.064000 x)))
(if 
(null (find-satisfiers '(preference_sb50_henceforth_satisfied) state T))
(setq x (+ 41.184000 x)))
(if 
(null (find-satisfiers '(preference_sb49_henceforth_satisfied) state T))
(setq x (+ 98.522700 x)))


(if 
(null (find-satisfiers '(preference_sb37_henceforth_satisfied) state T))
(setq x (+ 54.912000 x)))


(if 
(null (find-satisfiers '(preference_sb9_henceforth_satisfied) state T))
(setq x (+ 94.057600 x)))
(if 
(null (find-satisfiers '(preference_sb6_henceforth_satisfied) state T))
(setq x (+ 102.745000 x)))
(if 
(null (find-satisfiers '(preference_o14_henceforth_satisfied) state T))
(setq x (+ 51.480000 x)))
(if 
(null (find-satisfiers '(preference_o13_henceforth_satisfied) state T))
(setq x (+ 82.506700 x)))
(if 
(null (find-satisfiers '(preference_o12_henceforth_satisfied) state T))
(setq x (+ 54.340000 x)))
(if 
(null (find-satisfiers '(preference_o11_henceforth_satisfied) state T))
(setq x (+ 33.176000 x)))
(if 
(null (find-satisfiers '(preference_o10_henceforth_satisfied) state T))
(setq x (+ 59.488000 x)))
(if 
(null (find-satisfiers '(preference_o9_henceforth_satisfied) state T))
(setq x (+ 32.604000 x)))
(if 
(null (find-satisfiers '(preference_o8_henceforth_satisfied) state T))
(setq x (+ 61.776000 x)))
(if 
(null (find-satisfiers '(preference_o7_henceforth_satisfied) state T))
(setq x (+ 82.940000 x)))
(if 
(null (find-satisfiers '(preference_o6_henceforth_satisfied) state T))
(setq x (+ 63.058700 x)))
(if 
(null (find-satisfiers '(preference_o5_henceforth_satisfied) state T))
(setq x (+ 57.238100 x)))
(if 
(null (find-satisfiers '(preference_o4_henceforth_satisfied) state T))
(setq x (+ 53.404000 x)))
(if 
(null (find-satisfiers '(preference_o3_henceforth_satisfied) state T))
(setq x (+ 39.468000 x)))
(if 
(null (find-satisfiers '(preference_o2_henceforth_satisfied) state T))
(setq x (+ 39.468000 x)))
(if 
(null (find-satisfiers '(preference_o1_henceforth_satisfied) state T))
(setq x (+ 98.536500 x)))
(if 
(null (find-satisfiers '(preference_o0_henceforth_satisfied) state T))
(setq x (+ 63.492000 x)))
(if 
(null (find-satisfiers '(preference_e32_henceforth_satisfied) state T))
(setq x (+ 53.768000 x)))
(if 
(null (find-satisfiers '(preference_e31_henceforth_satisfied) state T))
(setq x (+ 82.940000 x)))
(if 
(null (find-satisfiers '(preference_e30_henceforth_satisfied) state T))
(setq x (+ 96.668000 x)))
(if 
(null (find-satisfiers '(preference_e29_henceforth_satisfied) state T))
(setq x (+ 63.058700 x)))
(if 
(null (find-satisfiers '(preference_e28_henceforth_satisfied) state T))
(setq x (+ 80.149300 x)))
;;(if 
;;(null (find-satisfiers '(preference_e27_henceforth_satisfied) state T))
;;(setq x (+ 69.628000 x)))
(if 
(null (find-satisfiers '(preference_e26_henceforth_satisfied) state T))
(setq x (+ 58.344000 x)))
(if 
(null (find-satisfiers '(preference_e25_henceforth_satisfied) state T))
(setq x (+ 35.464000 x)))
(if 
(null (find-satisfiers '(preference_e24_henceforth_satisfied) state T))
(setq x (+ 66.924000 x)))

(if 
(null (find-satisfiers '(preference_e22_henceforth_satisfied) state T))
(setq x (+ 74.360000 x)))
(if 
(null (find-satisfiers '(preference_e21_henceforth_satisfied) state T))
(setq x (+ 63.648000 x)))
(if 
(null (find-satisfiers '(preference_e20_henceforth_satisfied) state T))
(setq x (+ 50.336000 x)))
(if 
(null (find-satisfiers '(preference_e19_henceforth_satisfied) state T))
(setq x (+ 65.447200 x)))
(if 
(null (find-satisfiers '(preference_e18_henceforth_satisfied) state T))
(setq x (+ 77.740000 x)))
(if 
(null (find-satisfiers '(preference_e17_henceforth_satisfied) state T))
(setq x (+ 73.666700 x)))

(if 
(null (find-satisfiers '(preference_e15_henceforth_satisfied) state T))
(setq x (+ 85.800000 x)))
(if 
(null (find-satisfiers '(preference_e14_henceforth_satisfied) state T))
(setq x (+ 86.632000 x)))

(if 
(null (find-satisfiers '(preference_e10_henceforth_satisfied) state T))
(setq x (+ 37.297900 x)))

(if 
(null (find-satisfiers '(preference_e1_henceforth_satisfied) state T))
(setq x (+ 59.522700 x)))
(if 
(null (find-satisfiers '(preference_e0_henceforth_satisfied) state T))
(setq x (+ 70.720000 x)))
(if 
(null (find-satisfiers '(preference_a2_henceforth_satisfied) state T))
(setq x (+ 42.900000 x)))
(if 
(null (find-satisfiers '(preference_a1_henceforth_satisfied) state T))
(setq x (+ 72.072000 x)))
;(if 
;(null (find-satisfiers '(preference_a0_henceforth_satisfied) state T))
;(setq x (+ 81.224000 x)))
  (return-from pessimistic-metric x)
)
(defun optimistic-metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb246_optimistically_satisfied) state T))
(setq x (+ 75.036000 x)))
(if 
(null (find-satisfiers '(preference_sb241_optimistically_satisfied) state T))
(setq x (+ 68.640000 x)))
(if 
(null (find-satisfiers '(preference_sb233_optimistically_satisfied) state T))
(setq x (+ 33.748000 x)))
(if 
(null (find-satisfiers '(preference_sb231_optimistically_satisfied) state T))
(setq x (+ 63.648000 x)))
(if 
(null (find-satisfiers '(preference_sb218_optimistically_satisfied) state T))
(setq x (+ 35.949300 x)))
(if 
(null (find-satisfiers '(preference_sb199_optimistically_satisfied) state T))
(setq x (+ 44.044000 x)))
(if 
(null (find-satisfiers '(preference_sb198_optimistically_satisfied) state T))
(setq x (+ 60.060000 x)))
(if 
(null (find-satisfiers '(preference_sb195_optimistically_satisfied) state T))
(setq x (+ 30.316000 x)))
(if 
(null (find-satisfiers '(preference_sb193_optimistically_satisfied) state T))
(setq x (+ 41.520300 x)))
(if 
(null (find-satisfiers '(preference_sb184_optimistically_satisfied) state T))
(setq x (+ 51.480000 x)))

(if 
(null (find-satisfiers '(preference_sb172_optimistically_satisfied) state T))
(setq x (+ 91.728000 x)))
(if 
(null (find-satisfiers '(preference_sb159_optimistically_satisfied) state T))
(setq x (+ 55.986700 x)))
(if 
(null (find-satisfiers '(preference_sb158_optimistically_satisfied) state T))
(setq x (+ 53.404000 x)))
(if 
(null (find-satisfiers '(preference_sb157_optimistically_satisfied) state T))
(setq x (+ 45.188000 x)))
(if 
(null (find-satisfiers '(preference_sb156_optimistically_satisfied) state T))
(setq x (+ 55.484000 x)))
(if 
(null (find-satisfiers '(preference_sb155_optimistically_satisfied) state T))
(setq x (+ 80.652000 x)))
(if 
(null (find-satisfiers '(preference_sb148_optimistically_satisfied) state T))
(setq x (+ 42.224000 x)))

(if 
(null (find-satisfiers '(preference_sb135_optimistically_satisfied) state T))
(setq x (+ 47.853900 x)))
(if 
(null (find-satisfiers '(preference_sb123_optimistically_satisfied) state T))
(setq x (+ 54.912000 x)))
(if 
(null (find-satisfiers '(preference_sb122_optimistically_satisfied) state T))
(setq x (+ 42.900000 x)))
(if 
(null (find-satisfiers '(preference_sb121_optimistically_satisfied) state T))
(setq x (+ 72.072000 x)))
(if 
(null (find-satisfiers '(preference_sb117_optimistically_satisfied) state T))
(setq x (+ 69.212000 x)))
(if 
(null (find-satisfiers '(preference_sb105_optimistically_satisfied) state T))
(setq x (+ 90.521600 x)))
(if 
(null (find-satisfiers '(preference_sb96_optimistically_satisfied) state T))
(setq x (+ 44.044000 x)))
(if 
(null (find-satisfiers '(preference_sb95_optimistically_satisfied) state T))
(setq x (+ 91.291200 x)))
(if 
(null (find-satisfiers '(preference_sb93_optimistically_satisfied) state T))
(setq x (+ 63.336000 x)))
(if 
(null (find-satisfiers '(preference_sb87_optimistically_satisfied) state T))
(setq x (+ 83.744300 x)))

(if 
(null (find-satisfiers '(preference_sb80_optimistically_satisfied) state T))
(setq x (+ 75.434700 x)))
(if 
(null (find-satisfiers '(preference_sb79_optimistically_satisfied) state T))
(setq x (+ 30.888000 x)))
(if 
(null (find-satisfiers '(preference_sb77_optimistically_satisfied) state T))
(setq x (+ 64.896000 x)))

(if 
(null (find-satisfiers '(preference_sb63_optimistically_satisfied) state T))
(setq x (+ 70.356000 x)))
(if 
(null (find-satisfiers '(preference_sb53_optimistically_satisfied) state T))
(setq x (+ 64.064000 x)))
(if 
(null (find-satisfiers '(preference_sb50_optimistically_satisfied) state T))
(setq x (+ 41.184000 x)))
(if 
(null (find-satisfiers '(preference_sb49_optimistically_satisfied) state T))
(setq x (+ 98.522700 x)))

(if 
(null (find-satisfiers '(preference_sb37_optimistically_satisfied) state T))
(setq x (+ 54.912000 x)))
(if 
(null (find-satisfiers '(preference_sb9_optimistically_satisfied) state T))
(setq x (+ 94.057600 x)))
(if 
(null (find-satisfiers '(preference_sb6_optimistically_satisfied) state T))
(setq x (+ 102.745000 x)))
(if 
(null (find-satisfiers '(preference_o14_optimistically_satisfied) state T))
(setq x (+ 51.480000 x)))
(if 
(null (find-satisfiers '(preference_o13_optimistically_satisfied) state T))
(setq x (+ 82.506700 x)))
(if 
(null (find-satisfiers '(preference_o12_optimistically_satisfied) state T))
(setq x (+ 54.340000 x)))
(if 
(null (find-satisfiers '(preference_o11_optimistically_satisfied) state T))
(setq x (+ 33.176000 x)))
(if 
(null (find-satisfiers '(preference_o10_optimistically_satisfied) state T))
(setq x (+ 59.488000 x)))
(if 
(null (find-satisfiers '(preference_o9_optimistically_satisfied) state T))
(setq x (+ 32.604000 x)))
(if 
(null (find-satisfiers '(preference_o8_optimistically_satisfied) state T))
(setq x (+ 61.776000 x)))
(if 
(null (find-satisfiers '(preference_o7_optimistically_satisfied) state T))
(setq x (+ 82.940000 x)))
(if 
(null (find-satisfiers '(preference_o6_optimistically_satisfied) state T))
(setq x (+ 63.058700 x)))
(if 
(null (find-satisfiers '(preference_o5_optimistically_satisfied) state T))
(setq x (+ 57.238100 x)))
(if 
(null (find-satisfiers '(preference_o4_optimistically_satisfied) state T))
(setq x (+ 53.404000 x)))
(if 
(null (find-satisfiers '(preference_o3_optimistically_satisfied) state T))
(setq x (+ 39.468000 x)))
(if 
(null (find-satisfiers '(preference_o2_optimistically_satisfied) state T))
(setq x (+ 39.468000 x)))
(if 
(null (find-satisfiers '(preference_o1_optimistically_satisfied) state T))
(setq x (+ 98.536500 x)))
(if 
(null (find-satisfiers '(preference_o0_optimistically_satisfied) state T))
(setq x (+ 63.492000 x)))
(if 
(null (find-satisfiers '(preference_e32_optimistically_satisfied) state T))
(setq x (+ 53.768000 x)))
(if 
(null (find-satisfiers '(preference_e31_optimistically_satisfied) state T))
(setq x (+ 82.940000 x)))
(if 
(null (find-satisfiers '(preference_e30_optimistically_satisfied) state T))
(setq x (+ 96.668000 x)))
(if 
(null (find-satisfiers '(preference_e29_optimistically_satisfied) state T))
(setq x (+ 63.058700 x)))
(if 
(null (find-satisfiers '(preference_e28_optimistically_satisfied) state T))
(setq x (+ 80.149300 x)))
;;(if 
;;(null (find-satisfiers '(preference_e27_optimistically_satisfied) state T))
;;(setq x (+ 69.628000 x)))
(if 
(null (find-satisfiers '(preference_e26_optimistically_satisfied) state T))
(setq x (+ 58.344000 x)))
(if 
(null (find-satisfiers '(preference_e25_optimistically_satisfied) state T))
(setq x (+ 35.464000 x)))
(if 
(null (find-satisfiers '(preference_e24_optimistically_satisfied) state T))
(setq x (+ 66.924000 x)))

(if 
(null (find-satisfiers '(preference_e22_optimistically_satisfied) state T))
(setq x (+ 74.360000 x)))
(if 
(null (find-satisfiers '(preference_e21_optimistically_satisfied) state T))
(setq x (+ 63.648000 x)))
(if 
(null (find-satisfiers '(preference_e20_optimistically_satisfied) state T))
(setq x (+ 50.336000 x)))
(if 
(null (find-satisfiers '(preference_e19_optimistically_satisfied) state T))
(setq x (+ 65.447200 x)))
(if 
(null (find-satisfiers '(preference_e18_optimistically_satisfied) state T))
(setq x (+ 77.740000 x)))
(if 
(null (find-satisfiers '(preference_e17_optimistically_satisfied) state T))
(setq x (+ 73.666700 x)))

(if 
(null (find-satisfiers '(preference_e15_optimistically_satisfied) state T))
(setq x (+ 85.800000 x)))
(if 
(null (find-satisfiers '(preference_e14_optimistically_satisfied) state T))
(setq x (+ 86.632000 x)))

(if 
(null (find-satisfiers '(preference_e10_optimistically_satisfied) state T))
(setq x (+ 37.297900 x)))

(if 
(null (find-satisfiers '(preference_e1_optimistically_satisfied) state T))
(setq x (+ 59.522700 x)))
(if 
(null (find-satisfiers '(preference_e0_optimistically_satisfied) state T))
(setq x (+ 70.720000 x)))
(if 
(null (find-satisfiers '(preference_a2_optimistically_satisfied) state T))
(setq x (+ 42.900000 x)))
(if 
(null (find-satisfiers '(preference_a1_optimistically_satisfied) state T))
(setq x (+ 72.072000 x)))
;(if 
;(null (find-satisfiers '(preference_a0_optimistically_satisfied) state T))
;(setq x (+ 81.224000 x)))
  (return-from optimistic-metric x)
)


(defun bestMetric(&optional s)

  (return-from bestMetric  	 6314.47)
)