(defproblem p16  ROVER
  (
    ;;;
    ;;;  facts
    ;;;
    (LANDER GENERAL)
    (MODE COLOUR)
    (MODE HIGH_RES)
    (MODE LOW_RES)
    (ROVER ROVER0)
    (ROVER ROVER1)
    (ROVER ROVER2)
    (ROVER ROVER3)
    (STORE ROVER0STORE)
    (STORE ROVER1STORE)
    (STORE ROVER2STORE)
    (STORE ROVER3STORE)
    (WAYPOINT WAYPOINT0)
    (WAYPOINT WAYPOINT1)
    (WAYPOINT WAYPOINT2)
    (WAYPOINT WAYPOINT3)
    (WAYPOINT WAYPOINT4)
    (WAYPOINT WAYPOINT5)
    (WAYPOINT WAYPOINT6)
    (WAYPOINT WAYPOINT7)
    (WAYPOINT WAYPOINT8)
    (WAYPOINT WAYPOINT9)
    (WAYPOINT WAYPOINT10)
    (WAYPOINT WAYPOINT11)
    (CAMERA CAMERA0)
    (CAMERA CAMERA1)
    (CAMERA CAMERA2)
    (CAMERA CAMERA3)
    (OBJECTIVE OBJECTIVE0)
    (OBJECTIVE OBJECTIVE1)
    (OBJECTIVE OBJECTIVE2)
    (OBJECTIVE OBJECTIVE3)
    (OBJECTIVE OBJECTIVE4)
    ;;;
    ;;;  initial state Ts
    ;;;
    (VISIBLE WAYPOINT0 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT11)
    (VISIBLE WAYPOINT11 WAYPOINT0)
    (VISIBLE WAYPOINT1 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT1)
    (VISIBLE WAYPOINT2 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT2)
    (VISIBLE WAYPOINT3 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT3)
    (VISIBLE WAYPOINT3 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT3)
    (VISIBLE WAYPOINT4 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT11)
    (VISIBLE WAYPOINT11 WAYPOINT4)
    (VISIBLE WAYPOINT6 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT2)
    (VISIBLE WAYPOINT2 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT6)
    (VISIBLE WAYPOINT7 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT6)
    (VISIBLE WAYPOINT6 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT7)
    (VISIBLE WAYPOINT8 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT8)
    (VISIBLE WAYPOINT9 WAYPOINT0)
    (VISIBLE WAYPOINT0 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT1)
    (VISIBLE WAYPOINT1 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT4)
    (VISIBLE WAYPOINT4 WAYPOINT9)
    (VISIBLE WAYPOINT10 WAYPOINT5)
    (VISIBLE WAYPOINT5 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT10)
    (VISIBLE WAYPOINT11 WAYPOINT7)
    (VISIBLE WAYPOINT7 WAYPOINT11)
    (VISIBLE WAYPOINT11 WAYPOINT8)
    (VISIBLE WAYPOINT8 WAYPOINT11)
    (VISIBLE WAYPOINT11 WAYPOINT9)
    (VISIBLE WAYPOINT9 WAYPOINT11)
    (VISIBLE WAYPOINT11 WAYPOINT10)
    (VISIBLE WAYPOINT10 WAYPOINT11)
    (AT_SOIL_SAMPLE WAYPOINT0)
    (AT_SOIL_SAMPLE WAYPOINT1)
    (AT_ROCK_SAMPLE WAYPOINT1)
    (AT_ROCK_SAMPLE WAYPOINT2)
    (AT_ROCK_SAMPLE WAYPOINT3)
    (AT_SOIL_SAMPLE WAYPOINT4)
    (AT_SOIL_SAMPLE WAYPOINT5)
    (AT_ROCK_SAMPLE WAYPOINT5)
    (AT_SOIL_SAMPLE WAYPOINT7)
    (AT_SOIL_SAMPLE WAYPOINT8)
    (AT_ROCK_SAMPLE WAYPOINT8)
    (AT_SOIL_SAMPLE WAYPOINT9)
    (AT_ROCK_SAMPLE WAYPOINT9)
    (AT_ROCK_SAMPLE WAYPOINT10)
    (AT_SOIL_SAMPLE WAYPOINT11)
    (AT_ROCK_SAMPLE WAYPOINT11)
    (AT_LANDER GENERAL WAYPOINT6)
    (CHANNEL_FREE GENERAL)
    (AT ROVER0 WAYPOINT6)
    (AVAILABLE ROVER0)
    (STORE_OF ROVER0STORE ROVER0)
    (EMPTY ROVER0STORE)
    (EQUIPPED_FOR_SOIL_ANALYSIS ROVER0)
    (EQUIPPED_FOR_ROCK_ANALYSIS ROVER0)
    (EQUIPPED_FOR_IMAGING ROVER0)
    (CAN_TRAVERSE ROVER0 WAYPOINT6 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT6)
    (CAN_TRAVERSE ROVER0 WAYPOINT6 WAYPOINT2)
    (CAN_TRAVERSE ROVER0 WAYPOINT2 WAYPOINT6)
    (CAN_TRAVERSE ROVER0 WAYPOINT6 WAYPOINT7)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT6)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT0)
    (CAN_TRAVERSE ROVER0 WAYPOINT0 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT3)
    (CAN_TRAVERSE ROVER0 WAYPOINT3 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT1 WAYPOINT9)
    (CAN_TRAVERSE ROVER0 WAYPOINT9 WAYPOINT1)
    (CAN_TRAVERSE ROVER0 WAYPOINT2 WAYPOINT5)
    (CAN_TRAVERSE ROVER0 WAYPOINT5 WAYPOINT2)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT4)
    (CAN_TRAVERSE ROVER0 WAYPOINT4 WAYPOINT7)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT8)
    (CAN_TRAVERSE ROVER0 WAYPOINT8 WAYPOINT7)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT10)
    (CAN_TRAVERSE ROVER0 WAYPOINT10 WAYPOINT7)
    (CAN_TRAVERSE ROVER0 WAYPOINT7 WAYPOINT11)
    (CAN_TRAVERSE ROVER0 WAYPOINT11 WAYPOINT7)
    (AT ROVER1 WAYPOINT2)
    (AVAILABLE ROVER1)
    (STORE_OF ROVER1STORE ROVER1)
    (EMPTY ROVER1STORE)
    (EQUIPPED_FOR_SOIL_ANALYSIS ROVER1)
    (EQUIPPED_FOR_ROCK_ANALYSIS ROVER1)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT3)
    (CAN_TRAVERSE ROVER1 WAYPOINT3 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT5)
    (CAN_TRAVERSE ROVER1 WAYPOINT5 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT6)
    (CAN_TRAVERSE ROVER1 WAYPOINT6 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT9)
    (CAN_TRAVERSE ROVER1 WAYPOINT9 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT2 WAYPOINT10)
    (CAN_TRAVERSE ROVER1 WAYPOINT10 WAYPOINT2)
    (CAN_TRAVERSE ROVER1 WAYPOINT3 WAYPOINT1)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT3)
    (CAN_TRAVERSE ROVER1 WAYPOINT3 WAYPOINT8)
    (CAN_TRAVERSE ROVER1 WAYPOINT8 WAYPOINT3)
    (CAN_TRAVERSE ROVER1 WAYPOINT4 WAYPOINT7)
    (CAN_TRAVERSE ROVER1 WAYPOINT7 WAYPOINT4)
    (CAN_TRAVERSE ROVER1 WAYPOINT9 WAYPOINT11)
    (CAN_TRAVERSE ROVER1 WAYPOINT11 WAYPOINT9)
    (CAN_TRAVERSE ROVER1 WAYPOINT1 WAYPOINT0)
    (CAN_TRAVERSE ROVER1 WAYPOINT0 WAYPOINT1)
    (AT ROVER2 WAYPOINT9)
    (AVAILABLE ROVER2)
    (STORE_OF ROVER2STORE ROVER2)
    (EMPTY ROVER2STORE)
    (EQUIPPED_FOR_ROCK_ANALYSIS ROVER2)
    (EQUIPPED_FOR_IMAGING ROVER2)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT1)
    (CAN_TRAVERSE ROVER2 WAYPOINT1 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT2)
    (CAN_TRAVERSE ROVER2 WAYPOINT2 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT3)
    (CAN_TRAVERSE ROVER2 WAYPOINT3 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT9 WAYPOINT4)
    (CAN_TRAVERSE ROVER2 WAYPOINT4 WAYPOINT9)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT7)
    (CAN_TRAVERSE ROVER2 WAYPOINT7 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT8)
    (CAN_TRAVERSE ROVER2 WAYPOINT8 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT10)
    (CAN_TRAVERSE ROVER2 WAYPOINT10 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT0 WAYPOINT11)
    (CAN_TRAVERSE ROVER2 WAYPOINT11 WAYPOINT0)
    (CAN_TRAVERSE ROVER2 WAYPOINT2 WAYPOINT5)
    (CAN_TRAVERSE ROVER2 WAYPOINT5 WAYPOINT2)
    (CAN_TRAVERSE ROVER2 WAYPOINT2 WAYPOINT6)
    (CAN_TRAVERSE ROVER2 WAYPOINT6 WAYPOINT2)
    (AT ROVER3 WAYPOINT0)
    (AVAILABLE ROVER3)
    (STORE_OF ROVER3STORE ROVER3)
    (EMPTY ROVER3STORE)
    (EQUIPPED_FOR_ROCK_ANALYSIS ROVER3)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT8)
    (CAN_TRAVERSE ROVER3 WAYPOINT8 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT9)
    (CAN_TRAVERSE ROVER3 WAYPOINT9 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT10)
    (CAN_TRAVERSE ROVER3 WAYPOINT10 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT0 WAYPOINT11)
    (CAN_TRAVERSE ROVER3 WAYPOINT11 WAYPOINT0)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT3)
    (CAN_TRAVERSE ROVER3 WAYPOINT3 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT1 WAYPOINT6)
    (CAN_TRAVERSE ROVER3 WAYPOINT6 WAYPOINT1)
    (CAN_TRAVERSE ROVER3 WAYPOINT9 WAYPOINT4)
    (CAN_TRAVERSE ROVER3 WAYPOINT4 WAYPOINT9)
    (CAN_TRAVERSE ROVER3 WAYPOINT10 WAYPOINT2)
    (CAN_TRAVERSE ROVER3 WAYPOINT2 WAYPOINT10)
    (CAN_TRAVERSE ROVER3 WAYPOINT10 WAYPOINT5)
    (CAN_TRAVERSE ROVER3 WAYPOINT5 WAYPOINT10)
    (CAN_TRAVERSE ROVER3 WAYPOINT10 WAYPOINT7)
    (CAN_TRAVERSE ROVER3 WAYPOINT7 WAYPOINT10)
    (ON_BOARD CAMERA0 ROVER2)
    (CALIBRATION_TARGET CAMERA0 OBJECTIVE3)
    (SUPPORTS CAMERA0 LOW_RES)
    (ON_BOARD CAMERA1 ROVER2)
    (CALIBRATION_TARGET CAMERA1 OBJECTIVE4)
    (SUPPORTS CAMERA1 COLOUR)
    (ON_BOARD CAMERA2 ROVER0)
    (CALIBRATION_TARGET CAMERA2 OBJECTIVE2)
    (SUPPORTS CAMERA2 HIGH_RES)
    (ON_BOARD CAMERA3 ROVER2)
    (CALIBRATION_TARGET CAMERA3 OBJECTIVE3)
    (SUPPORTS CAMERA3 COLOUR)
    (SUPPORTS CAMERA3 HIGH_RES)
    (SUPPORTS CAMERA3 LOW_RES)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE0 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE1 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE2 WAYPOINT9)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE3 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT0)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT1)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT2)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT3)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT4)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT5)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT6)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT7)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT8)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT9)
    (VISIBLE_FROM OBJECTIVE4 WAYPOINT10)
(preference_sb0_prev_autstate_1_2)
(preference_sb0_prev_autstate_2_2)
(preference_sb0_prev_autstate_3_2)
(preference_sb1_prev_autstate_1_2)
(preference_sb1_prev_autstate_2_2)
(preference_sb1_prev_autstate_3_2)
(preference_sb2_prev_autstate_1_2)
(preference_sb2_prev_autstate_2_2)
(preference_sb2_prev_autstate_3_2)
(preference_sb3_prev_autstate_1_2)
(preference_sb3_prev_autstate_2_2)
(preference_sb3_prev_autstate_3_2)
(preference_sb4_prev_autstate_1_2)
(preference_sb4_prev_autstate_2_2)
(preference_sb4_prev_autstate_3_2)
(preference_sb5_prev_autstate_1_2)
(preference_sb5_prev_autstate_2_2)
(preference_sb5_prev_autstate_3_2)
(preference_sb6_prev_autstate_1_2)
(preference_sb6_prev_autstate_2_2)
(preference_sb6_prev_autstate_3_2)
(preference_sb7_prev_autstate_1_2)
(preference_sb7_prev_autstate_2_2)
(preference_sb7_prev_autstate_3_2)
(preference_sb8_prev_autstate_1_2)
(preference_sb8_prev_autstate_2_2)
(preference_sb8_prev_autstate_3_2)
(preference_sb9_prev_autstate_1_2)
(preference_sb9_prev_autstate_2_2)
(preference_sb9_prev_autstate_3_2)
(preference_sb10_prev_autstate_1_2)
(preference_sb10_prev_autstate_2_2)
(preference_sb10_prev_autstate_3_2)
(preference_sb11_prev_autstate_1_2)
(preference_sb11_prev_autstate_2_2)
(preference_sb11_prev_autstate_3_2)
(preference_sb20_prev_autstate_1_2)
(preference_sb20_prev_autstate_2_2)
(preference_sb20_prev_autstate_3_2)
(preference_sb12_prev_autstate_1_2)
(preference_sb12_prev_autstate_2_2)
(preference_sb12_prev_autstate_3_2)
(preference_sb21_prev_autstate_1_2)
(preference_sb21_prev_autstate_2_2)
(preference_sb21_prev_autstate_3_2)
(preference_sb30_prev_autstate_1_2)
(preference_sb30_prev_autstate_2_2)
(preference_sb30_prev_autstate_3_2)
(preference_sb13_prev_autstate_1_2)
(preference_sb13_prev_autstate_2_2)
(preference_sb13_prev_autstate_3_2)
(preference_sb22_prev_autstate_1_2)
(preference_sb22_prev_autstate_2_2)
(preference_sb22_prev_autstate_3_2)
(preference_sb31_prev_autstate_1_2)
(preference_sb31_prev_autstate_2_2)
(preference_sb31_prev_autstate_3_2)
(preference_sb14_prev_autstate_1_2)
(preference_sb14_prev_autstate_2_2)
(preference_sb14_prev_autstate_3_2)
(preference_sb23_prev_autstate_1_2)
(preference_sb23_prev_autstate_2_2)
(preference_sb23_prev_autstate_3_2)
(preference_sb32_prev_autstate_1_2)
(preference_sb32_prev_autstate_2_2)
(preference_sb32_prev_autstate_3_2)
(preference_sb15_prev_autstate_1_2)
(preference_sb15_prev_autstate_2_2)
(preference_sb15_prev_autstate_3_2)
(preference_sb24_prev_autstate_1_2)
(preference_sb24_prev_autstate_2_2)
(preference_sb24_prev_autstate_3_2)
(preference_sb33_prev_autstate_1_2)
(preference_sb33_prev_autstate_2_2)
(preference_sb33_prev_autstate_3_2)
(preference_sb16_prev_autstate_1_2)
(preference_sb16_prev_autstate_2_2)
(preference_sb16_prev_autstate_3_2)
(preference_sb25_prev_autstate_1_2)
(preference_sb25_prev_autstate_2_2)
(preference_sb25_prev_autstate_3_2)
(preference_sb34_prev_autstate_1_2)
(preference_sb34_prev_autstate_2_2)
(preference_sb34_prev_autstate_3_2)
(preference_sb17_prev_autstate_1_2)
(preference_sb17_prev_autstate_2_2)
(preference_sb17_prev_autstate_3_2)
(preference_sb26_prev_autstate_1_2)
(preference_sb26_prev_autstate_2_2)
(preference_sb26_prev_autstate_3_2)
(preference_sb18_prev_autstate_1_2)
(preference_sb18_prev_autstate_2_2)
(preference_sb18_prev_autstate_3_2)
(preference_sb27_prev_autstate_1_2)
(preference_sb27_prev_autstate_2_2)
(preference_sb27_prev_autstate_3_2)
(preference_sb19_prev_autstate_1_2)
(preference_sb19_prev_autstate_2_2)
(preference_sb19_prev_autstate_3_2)
(preference_sb28_prev_autstate_1_2)
(preference_sb28_prev_autstate_2_2)
(preference_sb28_prev_autstate_3_2)
(preference_sb29_prev_autstate_1_2)
(preference_sb29_prev_autstate_2_2)
(preference_sb29_prev_autstate_3_2)
(preference_e0_prev_autstate_1_2)
(preference_e1_prev_autstate_1_2)
(preference_e2_prev_autstate_1_2)
(preference_e3_prev_autstate_1_2)
(preference_e4_prev_autstate_1_2)
(preference_e5_prev_autstate_1_2)
(preference_e6_prev_autstate_1_2)
(preference_e7_prev_autstate_1_2)
(preference_e8_prev_autstate_1_2)
(preference_e9_prev_autstate_1_2)
(preference_o0_prev_autstate_1_2)
(preference_o1_prev_autstate_1_2)
(preference_o2_prev_autstate_1_2)
(preference_o3_prev_autstate_1_2)
(preference_o4_prev_autstate_1_2)
(preference_o5_prev_autstate_1_2)
(preference_o6_prev_autstate_1_2)
(preference_o7_prev_autstate_1_2)
(preference_o8_prev_autstate_1_2)
(preference_o9_prev_autstate_1_2)
(preference_e10_prev_autstate_1_2)
(preference_e11_prev_autstate_1_2)
(preference_e20_prev_autstate_1_2)
(preference_e12_prev_autstate_1_2)
(preference_e21_prev_autstate_1_2)
(preference_e30_prev_autstate_1_2)
(preference_e13_prev_autstate_1_2)
(preference_e22_prev_autstate_1_2)
(preference_e31_prev_autstate_1_2)
(preference_e40_prev_autstate_1_2)
(preference_e14_prev_autstate_1_2)
(preference_e23_prev_autstate_1_2)
(preference_e32_prev_autstate_1_2)
(preference_e41_prev_autstate_1_2)
(preference_e15_prev_autstate_1_2)
(preference_e24_prev_autstate_1_2)
(preference_e33_prev_autstate_1_2)
(preference_e42_prev_autstate_1_2)
(preference_e16_prev_autstate_1_2)
(preference_e25_prev_autstate_1_2)
(preference_e34_prev_autstate_1_2)
(preference_e43_prev_autstate_1_2)
(preference_e17_prev_autstate_1_2)
(preference_e26_prev_autstate_1_2)
(preference_e35_prev_autstate_1_2)
(preference_e18_prev_autstate_1_2)
(preference_e27_prev_autstate_1_2)
(preference_e36_prev_autstate_1_2)
(preference_e19_prev_autstate_1_2)
(preference_e28_prev_autstate_1_2)
(preference_e37_prev_autstate_1_2)
(preference_e29_prev_autstate_1_2)
(preference_e38_prev_autstate_1_2)
(preference_o10_prev_autstate_1_2)
(preference_e39_prev_autstate_1_2)
(preference_o11_prev_autstate_1_2)
(preference_o20_prev_autstate_1_2)
(preference_o12_prev_autstate_1_2)
(preference_o21_prev_autstate_1_2)
(preference_o13_prev_autstate_1_2)
(preference_o14_prev_autstate_1_2)
(preference_o15_prev_autstate_1_2)
(preference_o16_prev_autstate_1_2)
(preference_o17_prev_autstate_1_2)
(preference_o18_prev_autstate_1_2)
(preference_o19_prev_autstate_1_2)
(preference_sb0_prev_autstate_1_2)
(preference_sb0_prev_autstate_2_2)
(preference_sb0_prev_autstate_3_2)
(preference_sb1_prev_autstate_1_2)
(preference_sb1_prev_autstate_2_2)
(preference_sb1_prev_autstate_3_2)
(preference_sb2_prev_autstate_1_2)
(preference_sb2_prev_autstate_2_2)
(preference_sb2_prev_autstate_3_2)
(preference_sb3_prev_autstate_1_2)
(preference_sb3_prev_autstate_2_2)
(preference_sb3_prev_autstate_3_2)
(preference_sb4_prev_autstate_1_2)
(preference_sb4_prev_autstate_2_2)
(preference_sb4_prev_autstate_3_2)
(preference_sb5_prev_autstate_1_2)
(preference_sb5_prev_autstate_2_2)
(preference_sb5_prev_autstate_3_2)
(preference_sb6_prev_autstate_1_2)
(preference_sb6_prev_autstate_2_2)
(preference_sb6_prev_autstate_3_2)
(preference_sb7_prev_autstate_1_2)
(preference_sb7_prev_autstate_2_2)
(preference_sb7_prev_autstate_3_2)
(preference_sb8_prev_autstate_1_2)
(preference_sb8_prev_autstate_2_2)
(preference_sb8_prev_autstate_3_2)
(preference_sb9_prev_autstate_1_2)
(preference_sb9_prev_autstate_2_2)
(preference_sb9_prev_autstate_3_2)
(preference_sb10_prev_autstate_1_2)
(preference_sb10_prev_autstate_2_2)
(preference_sb10_prev_autstate_3_2)
(preference_sb11_prev_autstate_1_2)
(preference_sb11_prev_autstate_2_2)
(preference_sb11_prev_autstate_3_2)
(preference_sb20_prev_autstate_1_2)
(preference_sb20_prev_autstate_2_2)
(preference_sb20_prev_autstate_3_2)
(preference_sb12_prev_autstate_1_2)
(preference_sb12_prev_autstate_2_2)
(preference_sb12_prev_autstate_3_2)
(preference_sb21_prev_autstate_1_2)
(preference_sb21_prev_autstate_2_2)
(preference_sb21_prev_autstate_3_2)
(preference_sb30_prev_autstate_1_2)
(preference_sb30_prev_autstate_2_2)
(preference_sb30_prev_autstate_3_2)
(preference_sb13_prev_autstate_1_2)
(preference_sb13_prev_autstate_2_2)
(preference_sb13_prev_autstate_3_2)
(preference_sb22_prev_autstate_1_2)
(preference_sb22_prev_autstate_2_2)
(preference_sb22_prev_autstate_3_2)
(preference_sb31_prev_autstate_1_2)
(preference_sb31_prev_autstate_2_2)
(preference_sb31_prev_autstate_3_2)
(preference_sb14_prev_autstate_1_2)
(preference_sb14_prev_autstate_2_2)
(preference_sb14_prev_autstate_3_2)
(preference_sb23_prev_autstate_1_2)
(preference_sb23_prev_autstate_2_2)
(preference_sb23_prev_autstate_3_2)
(preference_sb32_prev_autstate_1_2)
(preference_sb32_prev_autstate_2_2)
(preference_sb32_prev_autstate_3_2)
(preference_sb15_prev_autstate_1_2)
(preference_sb15_prev_autstate_2_2)
(preference_sb15_prev_autstate_3_2)
(preference_sb24_prev_autstate_1_2)
(preference_sb24_prev_autstate_2_2)
(preference_sb24_prev_autstate_3_2)
(preference_sb33_prev_autstate_1_2)
(preference_sb33_prev_autstate_2_2)
(preference_sb33_prev_autstate_3_2)
(preference_sb16_prev_autstate_1_2)
(preference_sb16_prev_autstate_2_2)
(preference_sb16_prev_autstate_3_2)
(preference_sb25_prev_autstate_1_2)
(preference_sb25_prev_autstate_2_2)
(preference_sb25_prev_autstate_3_2)
(preference_sb34_prev_autstate_1_2)
(preference_sb34_prev_autstate_2_2)
(preference_sb34_prev_autstate_3_2)
(preference_sb17_prev_autstate_1_2)
(preference_sb17_prev_autstate_2_2)
(preference_sb17_prev_autstate_3_2)
(preference_sb26_prev_autstate_1_2)
(preference_sb26_prev_autstate_2_2)
(preference_sb26_prev_autstate_3_2)
(preference_sb18_prev_autstate_1_2)
(preference_sb18_prev_autstate_2_2)
(preference_sb18_prev_autstate_3_2)
(preference_sb27_prev_autstate_1_2)
(preference_sb27_prev_autstate_2_2)
(preference_sb27_prev_autstate_3_2)
(preference_sb19_prev_autstate_1_2)
(preference_sb19_prev_autstate_2_2)
(preference_sb19_prev_autstate_3_2)
(preference_sb28_prev_autstate_1_2)
(preference_sb28_prev_autstate_2_2)
(preference_sb28_prev_autstate_3_2)
(preference_sb29_prev_autstate_1_2)
(preference_sb29_prev_autstate_2_2)
(preference_sb29_prev_autstate_3_2)
(preference_e0_prev_autstate_1_2)
(preference_e1_prev_autstate_1_2)
(preference_e2_prev_autstate_1_2)
(preference_e3_prev_autstate_1_2)
(preference_e4_prev_autstate_1_2)
(preference_e5_prev_autstate_1_2)
(preference_e6_prev_autstate_1_2)
(preference_e7_prev_autstate_1_2)
(preference_e8_prev_autstate_1_2)
(preference_e9_prev_autstate_1_2)
(preference_o0_prev_autstate_1_2)
(preference_o1_prev_autstate_1_2)
(preference_o2_prev_autstate_1_2)
(preference_o3_prev_autstate_1_2)
(preference_o4_prev_autstate_1_2)
(preference_o5_prev_autstate_1_2)
(preference_o6_prev_autstate_1_2)
(preference_o7_prev_autstate_1_2)
(preference_o8_prev_autstate_1_2)
(preference_o9_prev_autstate_1_2)
(preference_e10_prev_autstate_1_2)
(preference_e11_prev_autstate_1_2)
(preference_e20_prev_autstate_1_2)
(preference_e12_prev_autstate_1_2)
(preference_e21_prev_autstate_1_2)
(preference_e30_prev_autstate_1_2)
(preference_e13_prev_autstate_1_2)
(preference_e22_prev_autstate_1_2)
(preference_e31_prev_autstate_1_2)
(preference_e40_prev_autstate_1_2)
(preference_e14_prev_autstate_1_2)
(preference_e23_prev_autstate_1_2)
(preference_e32_prev_autstate_1_2)
(preference_e41_prev_autstate_1_2)
(preference_e15_prev_autstate_1_2)
(preference_e24_prev_autstate_1_2)
(preference_e33_prev_autstate_1_2)
(preference_e42_prev_autstate_1_2)
(preference_e16_prev_autstate_1_2)
(preference_e25_prev_autstate_1_2)
(preference_e34_prev_autstate_1_2)
(preference_e43_prev_autstate_1_2)
(preference_e17_prev_autstate_1_2)
(preference_e26_prev_autstate_1_2)
(preference_e35_prev_autstate_1_2)
(preference_e18_prev_autstate_1_2)
(preference_e27_prev_autstate_1_2)
(preference_e36_prev_autstate_1_2)
(preference_e19_prev_autstate_1_2)
(preference_e28_prev_autstate_1_2)
(preference_e37_prev_autstate_1_2)
(preference_e29_prev_autstate_1_2)
(preference_e38_prev_autstate_1_2)
(preference_o10_prev_autstate_1_2)
(preference_e39_prev_autstate_1_2)
(preference_o11_prev_autstate_1_2)
(preference_o20_prev_autstate_1_2)
(preference_o12_prev_autstate_1_2)
(preference_o21_prev_autstate_1_2)
(preference_o13_prev_autstate_1_2)
(preference_o14_prev_autstate_1_2)
(preference_o15_prev_autstate_1_2)
(preference_o16_prev_autstate_1_2)
(preference_o17_prev_autstate_1_2)
(preference_o18_prev_autstate_1_2)
(preference_o19_prev_autstate_1_2)

  )
  ;;;
  ;;; goals
  ;;;
(:ordered (!!set-connectivity-info)
  ((achieve-goals (
    (COMMUNICATED_SOIL_DATA WAYPOINT4)
    (COMMUNICATED_SOIL_DATA WAYPOINT9)
    (COMMUNICATED_SOIL_DATA WAYPOINT1)
    (COMMUNICATED_SOIL_DATA WAYPOINT7)
    (COMMUNICATED_ROCK_DATA WAYPOINT3)
    (COMMUNICATED_ROCK_DATA WAYPOINT10)
    (COMMUNICATED_ROCK_DATA WAYPOINT5)
    (COMMUNICATED_ROCK_DATA WAYPOINT1)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE0 HIGH_RES)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE4 HIGH_RES)
    (COMMUNICATED_IMAGE_DATA OBJECTIVE2 HIGH_RES)
  ))))
)


(defun metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb34_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb33_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb32_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb31_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb30_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb29_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb28_satisfied) state T))
(setq x (+ 66.000000 x)))
(if 
(null (find-satisfiers '(preference_sb27_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb26_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb25_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb24_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb23_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb22_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb21_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb20_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb19_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb18_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb17_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb16_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_sb15_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb14_satisfied) state T))
(setq x (+ 54.000000 x)))

(if 
(null (find-satisfiers '(preference_sb1_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb0_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o21_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_o20_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o19_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o18_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o17_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o16_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o15_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o14_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o13_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o12_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o11_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o10_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o9_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o8_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o7_satisfied) state T))
(setq x (+ 72.000000 x)))
(if 
(null (find-satisfiers '(preference_o6_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o5_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o4_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_o3_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_o2_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o1_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o0_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e43_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e42_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e41_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e40_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e39_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e38_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_e37_satisfied) state T))
(setq x (+ 72.000000 x)))
(if 
(null (find-satisfiers '(preference_e36_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e35_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e34_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e33_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e32_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_e31_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e30_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e29_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e28_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e27_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e26_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e25_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e24_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e23_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e22_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e21_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e20_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e19_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e18_satisfied) state T))
(setq x (+ 54.000000 x)))

  (return-from metric x)
)
(defun pessimistic-metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb34_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb33_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb32_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb31_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb30_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb29_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb28_henceforth_satisfied) state T))
(setq x (+ 66.000000 x)))
(if 
(null (find-satisfiers '(preference_sb27_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb26_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb25_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb24_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb23_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb22_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb21_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb20_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb19_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb18_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb17_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb16_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_sb15_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb14_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))

(if 
(null (find-satisfiers '(preference_sb1_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb0_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o21_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_o20_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o19_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o18_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o17_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o16_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o15_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o14_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o13_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o12_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o11_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o10_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o9_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o8_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o7_henceforth_satisfied) state T))
(setq x (+ 72.000000 x)))
(if 
(null (find-satisfiers '(preference_o6_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o5_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o4_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_o3_henceforth_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_o2_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o1_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o0_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e43_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e42_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e41_henceforth_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e40_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e39_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e38_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_e37_henceforth_satisfied) state T))
(setq x (+ 72.000000 x)))
(if 
(null (find-satisfiers '(preference_e36_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e35_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e34_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e33_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e32_henceforth_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_e31_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e30_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e29_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e28_henceforth_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e27_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e26_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e25_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e24_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e23_henceforth_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e22_henceforth_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e21_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e20_henceforth_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e19_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e18_henceforth_satisfied) state T))
(setq x (+ 54.000000 x)))

  (return-from pessimistic-metric x)
)
(defun optimistic-metric (state) 
	(setq x 0)
(if 
(null (find-satisfiers '(preference_sb34_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb33_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb32_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb31_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb30_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb29_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb28_optimistically_satisfied) state T))
(setq x (+ 66.000000 x)))
(if 
(null (find-satisfiers '(preference_sb27_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb26_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb25_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb24_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb23_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_sb22_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb21_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb20_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb19_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb18_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb17_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_sb16_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_sb15_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb14_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))

(if 
(null (find-satisfiers '(preference_sb1_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_sb0_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o21_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_o20_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o19_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o18_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o17_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o16_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o15_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o14_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o13_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o12_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o11_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o10_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o9_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_o8_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o7_optimistically_satisfied) state T))
(setq x (+ 72.000000 x)))
(if 
(null (find-satisfiers '(preference_o6_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o5_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o4_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_o3_optimistically_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_o2_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o1_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_o0_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e43_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e42_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e41_optimistically_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e40_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e39_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e38_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_e37_optimistically_satisfied) state T))
(setq x (+ 72.000000 x)))
(if 
(null (find-satisfiers '(preference_e36_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e35_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e34_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e33_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e32_optimistically_satisfied) state T))
(setq x (+ 55.000000 x)))
(if 
(null (find-satisfiers '(preference_e31_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e30_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e29_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e28_optimistically_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e27_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e26_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e25_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e24_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e23_optimistically_satisfied) state T))
(setq x (+ 67.000000 x)))
(if 
(null (find-satisfiers '(preference_e22_optimistically_satisfied) state T))
(setq x (+ 64.000000 x)))
(if 
(null (find-satisfiers '(preference_e21_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e20_optimistically_satisfied) state T))
(setq x (+ 61.000000 x)))
(if 
(null (find-satisfiers '(preference_e19_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))
(if 
(null (find-satisfiers '(preference_e18_optimistically_satisfied) state T))
(setq x (+ 54.000000 x)))

  (return-from optimistic-metric x)
)


(defun bestMetric(&optional s)

  (return-from bestMetric  	 5918)
)


 

